#  Copyright (c) 2026. Jose Manuel Requena Plens
r"""Harmonic-distortion separation with exponential sweeps (Farina / Novak).

A single exponential sine sweep characterises the linear response and
every harmonic distortion order of a weakly nonlinear system at once:
after deconvolution, the distortion products of order ``n``
pack into separate impulse responses that *precede* the linear response by
the fixed advance (Farina, AES 108th Convention, 2000)

.. math::

   \Delta t_n = T \ln(n) / \ln(f_2/f_1) = L \ln(n),

where :math:`L = T / \ln(f_2/f_1)` is the sweep rate. Windowing each
arrival yields the **higher harmonic impulse responses** ``h_n(t)`` and
their Fourier transforms, the **higher harmonic frequency responses**
``H_n(f)`` (Novak, Lotton & Simon, JAES 63(10), 2015, Sec. 1.3), from
which the harmonic distortion is read as a function of the excitation
frequency with one measurement instead of a tone-by-tone sweep.

Two excitation/deconvolution pairs are implemented:

* **Synchronized swept-sine (Novak et al. 2015)** -- the sweep
  :math:`x(t) = \sin[2\pi f_1 L \exp(t/L)]` with the rate rounded so
  that :math:`f_1 L` is an integer (Eqs. 47/49). Time-shifting this
  signal by :math:`L \ln(n)` is then *exactly* equivalent to generating
  its n-th harmonic (Eq. 18), so the phases of the ``H_n(f)`` measure
  the system instead of the excitation. The impulse response is
  deconvolved with the closed-form spectrum of the inverse filter
  (Eq. 51) rather than an FFT of the signal, which extends the usable
  band of ``H_n`` to :math:`[n f_1, n f_2]` (their Fig. 6) and avoids
  inverting spectral ripple. Generated by
  :func:`synchronized_sweep_signal`; analysed with
  ``method="synchronized"`` (the default).

* **Exponential sweep with the Farina inverse filter** -- the classical
  ESS of :func:`phonometry.room.sweep_signal` deconvolved by the time-reversed,
  amplitude-compensated sweep (Farina 2000; ISO 18233:2006 Figure B.2,
  the machinery of :func:`phonometry.room.impulse_response`). The harmonic
  *magnitudes* are correct, but the sweep is not synchronized: its ``-1``
  phase term breaks the time-shift/harmonic equivalence, so the phases of
  ``H_n`` for :math:`n \ge 2` depend on the excitation and are not
  meaningful (Novak et al. 2015, Sec. 2.4 and Fig. 7). Use
  ``method="farina"`` to analyse recordings made with the existing ESS.

The memoryless polynomial oracle anchors both paths: driving
:math:`y = x + a_2 x^2 + a_3 x^3` with a unit sweep must return, by the
Chebyshev identities, :math:`\lvert H_1 \rvert = 1 + 3 a_3/4`,
:math:`\lvert H_2 \rvert = a_2/2` (phase :math:`-\pi/2`) and
:math:`\lvert H_3 \rvert = a_3/4` (phase :math:`\pi`), and a THD(f) equal to
the closed form :math:`\sqrt{(a_2/2)^2 + (a_3/4)^2} / (1 + 3 a_3/4)` -- which
also matches :func:`phonometry.electroacoustics.thd` measured tone by tone on
the same system.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Literal

import numpy as np

from ..io._resolve import apply_calibration, resolve_fs

if TYPE_CHECKING:
    from matplotlib.axes import Axes
    from numpy.typing import NDArray

    from ..io._signal import Signal

__all__ = [
    "SweptSineDistortionResult",
    "swept_sine_distortion",
    "synchronized_sweep_signal",
]

#: Minimum samples of a harmonic impulse-response window; anything shorter
#: cannot resolve a frequency response worth returning.
_MIN_IR_LENGTH = 16

#: Default cap for the automatic harmonic-window length, in samples (about
#: 170 ms at 48 kHz; plenty for the anechoic tail of driver measurements).
_DEFAULT_MAX_IR_LENGTH = 8192


def _positive(value: float, name: str) -> float:
    scalar = float(value)
    if not np.isfinite(scalar) or scalar <= 0.0:
        raise ValueError(f"'{name}' must be a positive, finite number.")
    return scalar


def _validate_sweep_band(fs: float, f1: float, f2: float) -> None:
    if f2 <= f1:
        raise ValueError("'f2' must be greater than 'f1'.")
    if f2 > fs / 2.0:
        raise ValueError("'f2' must not exceed the Nyquist frequency fs/2.")


def _sweep_rate(f1: float, f2: float, seconds: float) -> float:
    r"""Synchronized sweep rate ``L`` (Novak et al. 2015, Eq. 49).

    :math:`L = \operatorname{round}(f_1 \tilde{T} / \ln(f_2/f_1)) / f_1`:
    the rounding makes :math:`f_1 L` an integer number of periods so the
    sweep starts (and, when :math:`f_2/f_1` is an integer, ends) with
    exactly zero phase, which is the synchronization condition for
    meaningful harmonic phases (their Eqs. 30-32).
    """
    k = round(f1 * seconds / float(np.log(f2 / f1)))
    if k < 1:
        raise ValueError(
            "'seconds' is too short to synchronize the sweep: "
            "f1*seconds/ln(f2/f1) rounds to zero periods. Lengthen the "
            "sweep or raise 'f1'."
        )
    return k / f1


def synchronized_sweep_signal(
    fs: int,
    f1: float,
    f2: float,
    seconds: float,
    *,
    amplitude: float = 1.0,
    fade: float = 0.0,
) -> NDArray[np.float64]:
    r"""Generate a synchronized exponential sweep (Novak et al. 2015, Eq. 47).

    :math:`x(t) = A \sin[2\pi f_1 L \exp(t/L)]` with the rate
    :math:`L = \operatorname{round}(f_1 \tilde{T} / \ln(f_2/f_1)) / f_1`
    (Eq. 49, with ``seconds`` as the requested duration
    :math:`\tilde{T}`). Because
    :math:`f_1 L` is an integer, delaying the signal by :math:`L \ln(n)`
    is exactly equivalent to generating its n-th harmonic (Eq. 18), which
    is what makes the harmonic phases measured by
    :func:`swept_sine_distortion` properties of the system under test
    rather than of the excitation. The rounding adjusts the duration
    slightly: the generated signal lasts :math:`T = L \ln(f_2/f_1)`
    seconds rather than exactly ``seconds`` (the difference is at most
    :math:`\ln(f_2/f_1)/2` periods of ``f1``).

    :param fs: Sampling frequency in Hz.
    :param f1: Start frequency in Hz. Must be > 0.
    :param f2: Stop frequency in Hz. Must satisfy
        :math:`f_1 < f_2 \le f_\mathrm{s}/2`. When :math:`f_2/f_1` is an integer
        the sweep also *ends* with zero phase
        (Novak et al. 2015, Sec. 2.5).
    :param seconds: Approximate sweep duration in seconds; the exact
        duration is quantized by the synchronization rounding.
    :param amplitude: Peak amplitude of the sweep. Default 1.0.
    :param fade: Optional half-Hann fade-in/out as a fraction of the sweep
        duration (default 0.0: the analytic deconvolution assumes the
        unfaded sweep, and fades only reshape the band edges). Keep it
        small if the playback chain needs one, and pass the same value to
        :func:`swept_sine_distortion`.
    :return: The sweep samples, length :math:`\lceil T f_\mathrm{s} \rceil`.
    """
    fs_v = _positive(fs, "fs")
    f1_v = _positive(f1, "f1")
    _validate_sweep_band(fs_v, f1_v, float(f2))
    seconds_v = _positive(seconds, "seconds")
    amplitude_v = _positive(amplitude, "amplitude")
    if not 0.0 <= fade < 0.5:
        raise ValueError("fade must be in [0, 0.5)")
    rate = _sweep_rate(f1_v, float(f2), seconds_v)
    duration = rate * np.log(float(f2) / f1_v)
    n = int(np.ceil(duration * fs_v))
    t = np.arange(n) / fs_v
    sweep: NDArray[np.float64] = amplitude_v * np.sin(
        2.0 * np.pi * f1_v * rate * np.exp(t / rate)
    )
    if fade > 0.0:
        from ..room.impulse_response import _apply_fade

        sweep = _apply_fade(sweep, fade)
    return sweep


@dataclass(frozen=True)
class SweptSineDistortionResult:
    r"""Harmonic separation of a swept-sine measurement (Farina / Novak).

    Row ``k`` of the harmonic arrays describes order ``k + 1`` (row 0 is
    the linear response ``H1``). Each ``H_n`` lives on the common
    :attr:`frequencies` axis but only carries signal inside its own band:
    :math:`[n f_1, n f_2]` for the synchronized method,
    :math:`[n f_1, f_2]` for the Farina inverse filter (outside it there
    is only the measurement noise floor). The windowing delay is removed
    from the responses, so with the synchronized sweep the phases of
    ``H_n`` are system properties; with ``method="farina"`` only the
    magnitudes are meaningful.

    :ivar frequencies: Frequency axis of the harmonic responses, in Hz.
    :ivar harmonic_responses: Complex ``H_n(f)``, shape
        ``(n_harmonics, len(frequencies))``.
    :ivar harmonic_irs: Windowed harmonic impulse responses, shape
        ``(n_harmonics, ir_length)``; each is centred in its window (time
        zero at sample ``ir_length // 2``).
    :ivar delays: Arrival advances :math:`L \ln(n)` of each order before
        the linear response, in seconds.
    :ivar thd_frequencies: Excitation-frequency axis of the THD curve, Hz.
    :ivar thd: Total harmonic distortion at each excitation frequency
        :math:`f`:
        :math:`\sqrt{\sum_n \lvert H_n(n f) \rvert^2} / \lvert H_1(f)
        \rvert` over the orders available below Nyquist and inside their
        deconvolved band.
    :ivar distortion_ratios: Per-order ratios
        :math:`\lvert H_n(n f) \rvert / \lvert H_1(f) \rvert` on
        :attr:`thd_frequencies`; row ``k`` is order ``k + 2``. An order
        reads 0 where its product :math:`n f` leaves the valid band.
    :ivar fs: Sample rate, in Hz.
    :ivar f1: Sweep start frequency, in Hz.
    :ivar f2: Sweep stop frequency, in Hz.
    :ivar duration: Actual sweep duration ``T`` used by the analysis, s.
    :ivar rate: Sweep rate :math:`L = T / \ln(f_2/f_1)`, in seconds.
    :ivar method: ``"synchronized"`` or ``"farina"``.
    """

    frequencies: NDArray[np.float64]
    harmonic_responses: NDArray[np.complex128]
    harmonic_irs: NDArray[np.float64]
    delays: NDArray[np.float64]
    thd_frequencies: NDArray[np.float64]
    thd: NDArray[np.float64]
    distortion_ratios: NDArray[np.float64]
    fs: float
    f1: float
    f2: float
    duration: float
    rate: float
    method: str

    @property
    def n_harmonics(self) -> int:
        """Number of separated harmonic orders (including the linear H1)."""
        return int(self.harmonic_responses.shape[0])

    def plot(
        self, ax: Axes | None = None, *, language: str = "en", **kwargs: Any
    ) -> Axes | NDArray[Any]:
        """Plot the harmonic responses and the THD(f).

        Two stacked panels: the magnitudes of ``H1..HN`` in dB against
        their own frequency axes, and the total harmonic distortion in %
        against the excitation frequency. With ``ax`` given, only the THD
        panel is drawn on it.

        :param language: Label language, ``"en"`` (default) or ``"es"``.
        """
        from .._i18n import check_language
        from .._plot.electroacoustics import plot_swept_sine_distortion

        check_language(language)
        return plot_swept_sine_distortion(self, ax=ax, language=language, **kwargs)


def _analytic_inverse_spectrum(
    freqs: NDArray[np.float64], rate: float, f1: float
) -> NDArray[np.complex128]:
    r"""Closed-form inverse-filter spectrum (Novak et al. 2015, Eq. 51).

    .. math::

       \tilde{X}(f) = 2 \sqrt{f/L}
       \exp\left(-j 2\pi f L (1 - \ln(f/f_1)) + j\pi/4\right),

    the analytic reciprocal of the stationary-phase sweep spectrum; the DC
    bin is set to zero (their Sec. A.2.4).
    """
    with np.errstate(divide="ignore", invalid="ignore"):
        f_safe = np.maximum(freqs, np.finfo(np.float64).tiny)
        spectrum = (
            2.0
            * np.sqrt(f_safe / rate)
            * np.exp(
                -2j * np.pi * freqs * rate * (1.0 - np.log(f_safe / f1))
                + 1j * np.pi / 4.0
            )
        )
    spectrum[0] = 0.0
    return np.asarray(spectrum, dtype=np.complex128)


def _deconvolve_synchronized(
    rec: NDArray[np.float64],
    fs: float,
    f1: float,
    rate: float,
    pad: int,
) -> NDArray[np.float64]:
    r"""Deconvolve with the analytic inverse spectrum (Novak Eqs. 50-51).

    Returns the circular deconvolution buffer: the linear response starts
    at index 0 and the order-``n`` responses sit at :math:`-L \ln(n)`
    (i.e. wrapped to the tail). ``pad`` extra samples keep the wrapped
    harmonic arrivals clear of the causal tail.
    """
    nfft = int(2 ** np.ceil(np.log2(rec.size + pad)))
    spectrum = np.fft.rfft(rec, nfft) / fs
    freqs = np.asarray(np.fft.rfftfreq(nfft, 1.0 / fs), dtype=np.float64)
    return np.asarray(
        np.fft.irfft(spectrum * _analytic_inverse_spectrum(freqs, rate, f1), nfft),
        dtype=np.float64,
    )


def _deconvolve_farina(
    rec: NDArray[np.float64],
    fs: float,
    f1: float,
    f2: float,
    seconds: float,
    fade: float,
) -> NDArray[np.float64]:
    """Deconvolve with the Farina inverse filter (ISO 18233 Figure B.2).

    Linear (non-circular) convolution with the time-reversed,
    +6 dB/octave-compensated sweep, rolled so the linear response starts at
    index 0 and the harmonic advances wrap to the tail -- the same layout
    as the synchronized path.
    """
    from scipy import signal as sp_signal

    from ..room.impulse_response import inverse_filter

    inv = inverse_filter(int(fs), f1, f2, seconds, fade=fade)
    conv = sp_signal.fftconvolve(rec, inv)
    return np.asarray(np.roll(conv, -(inv.size - 1)), dtype=np.float64)


def _window_harmonics(
    buffer: NDArray[np.float64],
    delays_samples: NDArray[np.float64],
    ir_length: int,
) -> tuple[NDArray[np.float64], NDArray[np.complex128]]:
    """Extract each harmonic IR and its response (Novak Sec. A.2.5).

    Each order is cut in a window of ``ir_length`` samples centred on its
    (generally non-integer) arrival ``-delays_samples[n]``: the integer
    part selects the window, the fractional remainder is removed in the
    frequency domain with the shift theorem, and the centring delay of
    ``ir_length // 2`` samples is compensated so the returned responses
    carry the system phase only.
    """
    n_orders = delays_samples.size
    half = ir_length // 2
    total = buffer.size
    omega = 2.0 * np.pi * np.arange(ir_length // 2 + 1) / ir_length
    irs = np.empty((n_orders, ir_length), dtype=np.float64)
    responses = np.empty((n_orders, ir_length // 2 + 1), dtype=np.complex128)
    centering = np.exp(1j * omega * half)
    base = np.arange(ir_length)
    for k in range(n_orders):
        advance = int(np.round(delays_samples[k]))
        remainder = delays_samples[k] - advance
        start = (total - advance - half) % total
        segment = buffer[(start + base) % total]
        spectrum = np.fft.rfft(segment) * np.exp(-1j * remainder * omega)
        irs[k] = np.fft.irfft(spectrum, ir_length)
        responses[k] = spectrum * centering
    return irs, responses


def _thd_curves(
    frequencies: NDArray[np.float64],
    responses: NDArray[np.complex128],
    fs: float,
    f1: float,
    f2: float,
    method: str,
) -> tuple[NDArray[np.float64], NDArray[np.float64], NDArray[np.float64]]:
    r"""THD(f) and per-order ratios referenced to the fundamental.

    At each excitation frequency :math:`f` the order-``n`` product is
    read at :math:`n f` from ``H_n`` (linear interpolation on the common
    grid) if the product stays below Nyquist and inside the deconvolved
    band of that order (:math:`n f_2` for the synchronized method,
    ``f2`` for the Farina inverse filter); otherwise the order
    contributes zero. The grid is
    limited to the excitation range where the order-2 product exists, so
    THD never silently reads 0 for lack of any measurable harmonic.
    """
    n_orders = responses.shape[0]
    upper_band = f2 if method == "farina" else None
    f_max = min(f2, fs / 2.0 / 2.0)
    if upper_band is not None:
        f_max = min(f_max, upper_band / 2.0)
    grid = (frequencies >= f1) & (frequencies <= f_max)
    if not np.any(grid):
        raise ValueError(
            f"no excitation-frequency bin has a measurable order-2 "
            f"product: the THD grid [{f1:.6g}, {f_max:.6g}] Hz is empty at "
            f"the {frequencies[1]:.6g}-Hz window resolution. Lower 'f1' "
            "(the order-2 product must stay below Nyquist) or raise "
            "'ir_length' for a finer grid."
        )
    thd_freqs = frequencies[grid]
    fundamental = np.abs(responses[0][grid])
    ratios = np.zeros((max(n_orders - 1, 0), thd_freqs.size), dtype=np.float64)
    tiny = np.finfo(np.float64).tiny
    for k in range(1, n_orders):
        order = k + 1
        product = order * thd_freqs
        level = np.interp(
            product, frequencies, np.abs(responses[k]), left=0.0, right=0.0
        )
        top = min(order * f2 if upper_band is None else upper_band, fs / 2.0)
        level[(product < order * f1) | (product > top)] = 0.0
        ratios[k - 1] = level / np.maximum(fundamental, tiny)
    thd = np.sqrt(np.sum(ratios**2, axis=0))
    return thd_freqs, thd, ratios


def _default_ir_length(min_spacing: int) -> int:
    """Largest power of two <= ``min_spacing`` (capped), for fast FFTs."""
    capped = min(min_spacing, _DEFAULT_MAX_IR_LENGTH)
    if capped < _MIN_IR_LENGTH:
        return capped  # let the caller raise with the sizing message
    return int(2 ** int(np.floor(np.log2(capped))))


def _validated_recording(
    recorded: Signal | NDArray[np.float64] | list[float],
) -> NDArray[np.float64]:
    rec = np.asarray(recorded, dtype=np.float64)
    if rec.ndim != 1:
        raise ValueError("'recorded' must be one-dimensional.")
    if not np.all(np.isfinite(rec)):
        raise ValueError("'recorded' must be finite.")
    return rec


def _sweep_timing(
    method: str, fs: float, f1: float, f2: float, seconds: float
) -> tuple[float, float, int]:
    r"""Return ``(rate L, duration T, sweep_samples)`` for either generator.

    Mirrors the exact quantization of the matching excitation:
    :func:`synchronized_sweep_signal` rounds the rate (Novak Eq. 49) and
    lasts :math:`\lceil T f_\mathrm{s} \rceil` samples;
    :func:`phonometry.room.sweep_signal` rounds
    the duration to ``round(seconds*fs)`` samples.
    """
    if method == "synchronized":
        rate = _sweep_rate(f1, f2, seconds)
        duration = float(rate * np.log(f2 / f1))
        return rate, duration, int(np.ceil(duration * fs))
    sweep_samples = round(seconds * fs)
    duration = sweep_samples / fs
    return duration / float(np.log(f2 / f1)), duration, sweep_samples


def _harmonic_window(
    ir_length: int | None,
    delays_samples: NDArray[np.float64],
    n_orders: int,
) -> int:
    """Resolve and validate the per-order window length, in samples.

    The window (explicit, or the largest power of two that fits) must not
    exceed the spacing between the two closest arrivals -- orders
    ``n_orders - 1`` and ``n_orders`` -- or the windows would overlap.
    """
    min_spacing = int(np.floor(delays_samples[-1] - delays_samples[-2]))
    if ir_length is not None:
        window = int(ir_length)
        if window < _MIN_IR_LENGTH:
            raise ValueError(f"'ir_length' must be at least {_MIN_IR_LENGTH} samples.")
    else:
        window = _default_ir_length(min_spacing)
        if window < _MIN_IR_LENGTH:
            raise ValueError(
                f"the harmonic windows would be {window} samples long "
                f"(minimum {_MIN_IR_LENGTH}); the two closest arrivals are "
                f"only {min_spacing} samples apart. Lengthen the sweep or "
                "lower 'n_harmonics'."
            )
    if window > min_spacing:
        raise ValueError(
            f"'ir_length' ({window}) exceeds the {min_spacing}-sample "
            f"spacing between orders {n_orders - 1} and {n_orders}; the "
            "windows would overlap. Shorten 'ir_length', lengthen the "
            "sweep or lower 'n_harmonics'."
        )
    return window


def _check_farina_span(
    delays_samples: NDArray[np.float64],
    window: int,
    sweep_samples: int,
    f1: float,
    f2: float,
    n_orders: int,
) -> None:
    """Reject orders the linear Farina deconvolution cannot hold.

    The Farina buffer is a linear convolution: its anticausal span is only
    inverse-filter-length - 1 = ``sweep_samples - 1`` samples. An order
    arriving beyond it (n > f2/f1, up to the window half-width) would wrap
    onto the causal linear response and read back a spurious copy of H1.
    """
    anticausal = sweep_samples - 1
    if delays_samples[-1] + window / 2.0 <= anticausal:
        return
    if delays_samples[-1] > anticausal:
        cause = (
            f"method='farina' can only separate orders up to the "
            f"sweep frequency ratio f2/f1 = {f2 / f1:.2f}: "
            f"order {n_orders} arrives {delays_samples[-1]:.0f} "
            f"samples before the linear response, beyond the "
            f"{anticausal}-sample anticausal span of the linear "
            "deconvolution. Lower 'n_harmonics' or widen the "
            "sweep band."
        )
    else:
        cause = (
            f"the {window}-sample window around the order-"
            f"{n_orders} arrival ({delays_samples[-1]:.0f} samples "
            f"before the linear response) does not fit the "
            f"{anticausal}-sample anticausal span of the linear "
            "Farina deconvolution. Shorten 'ir_length', lower "
            "'n_harmonics' or lengthen the sweep."
        )
    raise ValueError(cause)


def swept_sine_distortion(
    recorded: Signal | NDArray[np.float64] | list[float],
    fs: float | None = None,
    *,
    f1: float,
    f2: float,
    seconds: float,
    method: Literal["synchronized", "farina"] = "synchronized",
    n_harmonics: int = 5,
    ir_length: int | None = None,
    amplitude: float = 1.0,
    fade: float | None = None,
    remove_dc: bool = True,
) -> SweptSineDistortionResult:
    r"""Separate the harmonic responses of a swept-sine measurement.

    Deconvolves the recorded response of a (weakly, memorylessly) nonlinear
    system to an exponential sweep and windows the impulse response of each
    distortion order at its exact arrival :math:`-L \ln(n)` (Farina 2000;
    Novak et al. 2015). Returns the linear response ``H1`` and the higher
    harmonic frequency responses ``H2..HN`` together with the total
    harmonic distortion as a function of the excitation frequency.

    The excitation must be the matching generator with the *same*
    parameters: :func:`synchronized_sweep_signal` for
    ``method="synchronized"`` (the default; harmonic phases are meaningful,
    and the closed-form deconvolution extends each ``H_n`` to
    :math:`[n f_1, n f_2]`), or :func:`phonometry.room.sweep_signal` for
    ``method="farina"`` (magnitudes only; the band of every ``H_n`` is
    capped at ``f2`` by the inverse filter).

    :param recorded: Recorded system response (1-D). Include enough
        trailing room for the system to decay; at least the sweep length.
        Accepts a :class:`phonometry.io.Signal`, whose calibration is
        applied to the samples: ``harmonic_responses`` and ``harmonic_irs``
        carry the unit and so come out in pascals per unit of excitation,
        while ``thd`` and ``distortion_ratios`` are ratios of harmonics
        drawn from the same record and do not move.
    :param fs: Sample rate, in Hz. Required for a bare array; a
        :class:`~phonometry.io.Signal` brings its own, and an explicit value
        that disagrees with it raises instead of silently winning.
    :param f1: Sweep start frequency, in Hz.
    :param f2: Sweep stop frequency, in Hz. Distortion products above
        Nyquist fold back in any real recording, so keep
        ``n_harmonics*f2`` in mind when choosing the sweep band.
    :param seconds: Sweep duration handed to the generator, in seconds
        (for the synchronized method the actual duration is the same
        quantized value the generator used).
    :param method: ``"synchronized"`` (Novak et al. 2015, default) or
        ``"farina"`` (classical ESS with the Farina inverse filter).
    :param n_harmonics: Highest harmonic order to separate (>= 2,
        default 5).
    :param ir_length: Window length per harmonic IR, in samples. Default:
        the largest power of two that fits the closest harmonic spacing
        (at most 8192). Must not exceed the spacing
        ``L*ln(n_harmonics/(n_harmonics-1))*fs`` between the two closest
        arrivals, or the windows would overlap.
    :param amplitude: Peak amplitude the excitation was generated with.
        The recording is referenced to it, so ``H1`` is the linear gain
        and the THD is amplitude-referenced exactly as measured.
    :param fade: Fade fraction the excitation was generated with, or
        ``None`` for the generator's default (0.0 synchronized, 0.01
        Farina). Only used by ``method="farina"`` to rebuild the inverse
        filter; the synchronized deconvolution is analytic.
    :param remove_dc: Subtract the recording mean before deconvolving
        (default True). A DC offset otherwise leaks a scaled copy of the
        inverse filter into the impulse response (Novak et al. 2015,
        Sec. A.2.3).
    :return: A :class:`SweptSineDistortionResult`.
    :raises ValueError: If the inputs are invalid; if ``ir_length``
        (explicit or default) cannot fit between the harmonic arrivals --
        lengthen the sweep, lower ``n_harmonics`` or pass a shorter
        ``ir_length``; if ``method="farina"`` is asked for orders beyond
        the anticausal span of its linear deconvolution; or if no
        excitation frequency has a measurable order-2 product (``f1``
        above ``fs/4``, where every order-2 product would exceed Nyquist).
    """
    fs = resolve_fs(recorded, fs, name="recorded")
    rec = apply_calibration(recorded, _validated_recording(recorded))
    fs_v = _positive(fs, "fs")
    f1_v = _positive(f1, "f1")
    f2_v = _positive(f2, "f2")
    _validate_sweep_band(fs_v, f1_v, f2_v)
    seconds_v = _positive(seconds, "seconds")
    amplitude_v = _positive(amplitude, "amplitude")
    if method not in ("synchronized", "farina"):
        raise ValueError("'method' must be 'synchronized' or 'farina'.")
    n_orders = int(n_harmonics)
    if n_orders < 2:
        raise ValueError("'n_harmonics' must be at least 2.")

    rate, duration, sweep_samples = _sweep_timing(method, fs_v, f1_v, f2_v, seconds_v)
    if rec.size < sweep_samples:
        raise ValueError(
            f"'recorded' has {rec.size} samples but the sweep lasts "
            f"{sweep_samples}; record at least the whole sweep (plus the "
            "system decay)."
        )

    orders = np.arange(1, n_orders + 1, dtype=np.float64)
    delays_samples = rate * np.log(orders) * fs_v
    window = _harmonic_window(ir_length, delays_samples, n_orders)
    if method == "farina":
        _check_farina_span(delays_samples, window, sweep_samples, f1_v, f2_v, n_orders)

    signal = rec / amplitude_v
    if remove_dc:
        signal = signal - float(np.mean(signal))

    if method == "synchronized":
        pad = int(np.ceil(delays_samples[-1])) + window
        buffer = _deconvolve_synchronized(signal, fs_v, f1_v, rate, pad)
    else:
        fade_v = 0.01 if fade is None else float(fade)
        buffer = _deconvolve_farina(signal, fs_v, f1_v, f2_v, seconds_v, fade_v)

    irs, responses = _window_harmonics(buffer, delays_samples, window)
    frequencies = np.asarray(np.fft.rfftfreq(window, 1.0 / fs_v), dtype=np.float64)
    thd_freqs, thd, ratios = _thd_curves(
        frequencies, responses, fs_v, f1_v, f2_v, method
    )
    return SweptSineDistortionResult(
        frequencies=frequencies,
        harmonic_responses=responses,
        harmonic_irs=irs,
        delays=delays_samples / fs_v,
        thd_frequencies=thd_freqs,
        thd=thd,
        distortion_ratios=ratios,
        fs=fs_v,
        f1=f1_v,
        f2=f2_v,
        duration=float(duration),
        rate=float(rate),
        method=method,
    )
