#  Copyright (c) 2026. Jose Manuel Requena Plens
"""emission domain of phonometry (see module docstrings)."""

from __future__ import annotations

from .._plot.geometry import (
    plot_microphone_positions,
    plot_pp_probe_geometry,
)
from .declaration import (
    DeclarationForm,
    NoiseEmissionDeclaration,
    OperatingModeDeclaration,
)
from .intensity import (
    TEMPORAL_VARIABILITY_LIMIT,
    FieldIndicators,
    IntensityResult,
    dynamic_capability_index,
    field_indicators,
    sound_intensity,
    temporal_variability_indicator,
)
from .intensity_compliance import (
    IntensityInstrumentComplianceResult,
    instrument_class_from_components,
    intensity_class_compliance,
    phase_mismatch_from_residual_index,
    residual_index_from_phase_mismatch,
    residual_index_limits,
    verify_intensity_class,
)
from .sound_power import (
    RoomEnvironment,
    SoundPowerResult,
    SoundPowerWarning,
    background_noise_correction,
    environmental_correction,
    measurement_positions,
    sound_power_pressure,
)
from .sound_power_anechoic import (
    MeteorologicalCorrection,
    PrecisionSoundPowerResult,
    meteorological_corrections,
    precision_background_correction,
    precision_positions,
    precision_uncertainty,
    sound_power_anechoic,
)
from .sound_power_in_situ import (
    InSituSoundPowerResult,
    excess_sound_pressure_level,
    sound_energy_in_situ,
    sound_power_in_situ,
    static_pressure_from_altitude,
)
from .sound_power_intensity import (
    PrecisionCriteria,
    PrecisionFieldIndicators,
    PrecisionIntensityResult,
    SoundPowerIntensityResult,
    precision_field_indicators,
    precision_qualification,
    sound_power_intensity,
    sound_power_intensity_precision,
)
from .sound_power_intensity_points import (
    ActionCode,
    DiscretePointIntensityResult,
    PartialPowerConcentration,
    determination_standard_deviation,
    error_factor,
    normal_intensity_from_levels,
    partial_power_concentration,
    position_count_factor,
    sound_power_intensity_points,
)
from .sound_power_reverberation import (
    ReverberationSoundPowerResult,
    sound_power_comparison,
    sound_power_reverberation,
)
from .vibration_sound_power import (
    NORMALIZED_IMPEDANCE,
    REFERENCE_VELOCITY,
    VibrationSoundPowerResult,
    extraneous_velocity_correction,
    mean_velocity_level,
    radiated_sound_power_level,
    radiation_factor,
    sound_power_from_vibration,
    velocity_level,
    velocity_level_from_acceleration,
)

__all__ = [
    "NORMALIZED_IMPEDANCE",
    "REFERENCE_VELOCITY",
    "TEMPORAL_VARIABILITY_LIMIT",
    "ActionCode",
    "DeclarationForm",
    "DiscretePointIntensityResult",
    "FieldIndicators",
    "InSituSoundPowerResult",
    "IntensityInstrumentComplianceResult",
    "IntensityResult",
    "MeteorologicalCorrection",
    "NoiseEmissionDeclaration",
    "OperatingModeDeclaration",
    "PartialPowerConcentration",
    "PrecisionCriteria",
    "PrecisionFieldIndicators",
    "PrecisionIntensityResult",
    "PrecisionSoundPowerResult",
    "ReverberationSoundPowerResult",
    "RoomEnvironment",
    "SoundPowerIntensityResult",
    "SoundPowerResult",
    "SoundPowerWarning",
    "VibrationSoundPowerResult",
    "background_noise_correction",
    "determination_standard_deviation",
    "dynamic_capability_index",
    "environmental_correction",
    "error_factor",
    "excess_sound_pressure_level",
    "extraneous_velocity_correction",
    "field_indicators",
    "instrument_class_from_components",
    "intensity_class_compliance",
    "mean_velocity_level",
    "measurement_positions",
    "meteorological_corrections",
    "normal_intensity_from_levels",
    "partial_power_concentration",
    "phase_mismatch_from_residual_index",
    "plot_microphone_positions",
    "plot_pp_probe_geometry",
    "position_count_factor",
    "precision_background_correction",
    "precision_field_indicators",
    "precision_positions",
    "precision_qualification",
    "precision_uncertainty",
    "radiated_sound_power_level",
    "radiation_factor",
    "residual_index_from_phase_mismatch",
    "residual_index_limits",
    "sound_energy_in_situ",
    "sound_intensity",
    "sound_power_anechoic",
    "sound_power_comparison",
    "sound_power_from_vibration",
    "sound_power_in_situ",
    "sound_power_intensity",
    "sound_power_intensity_points",
    "sound_power_intensity_precision",
    "sound_power_pressure",
    "sound_power_reverberation",
    "static_pressure_from_altitude",
    "temporal_variability_indicator",
    "velocity_level",
    "velocity_level_from_acceleration",
    "verify_intensity_class",
]
