#  Copyright (c) 2026. Jose Manuel Requena Plens
"""vibration.structural subdomain of phonometry: structural vibration: mobility, junctions, radiation and SEA."""

from __future__ import annotations

from .experimental_sea import (
    PowerInjectionResult,
    bar_modal_density,
    beam_modal_density,
    cylindrical_shell_modal_density,
    flat_plate_modal_density,
    power_injection_clf,
    power_injection_matrix,
    ring_frequency,
)
from .junction_transmission import (
    JunctionTransmissionResult,
    angular_average_transmission_coefficient,
    corner_transmission_coefficient,
    coupling_loss_factor,
    inline_transmission_coefficient,
    junction_transmission,
    junction_wave_parameters,
    point_connection_coupling_loss_factor,
    right_angle_transmission_coefficient,
    straight_transmission_coefficient,
    wave_vibration_reduction_index,
)
from .mechanical_mobility import (
    FRF_UNITS,
    MobilityResult,
    RigidMassCalibrationResult,
    convert_frf,
    random_error_percent,
    resonance_frequency,
    rigid_mass_calibration_check,
    sdof_accelerance,
    sdof_mobility,
    sdof_mobility_result,
    sdof_receptance,
)
from .point_mobility import (
    beam_bending_wave_speed,
    infinite_beam_impedance,
    infinite_beam_mobility,
    infinite_beam_moment_mobility,
    infinite_beam_point_mobility,
    infinite_plate_impedance,
    infinite_plate_mobility,
    infinite_plate_point_mobility,
    injected_power,
    longitudinal_rod_impedance,
    longitudinal_rod_mobility,
    plate_bending_stiffness,
    plate_bending_wave_speed,
)
from .radiation_efficiency import (
    RadiationEfficiencyResult,
    coincidence_frequency,
    radiation_efficiency,
)
from .transfer_stiffness import (
    REFERENCE_STIFFNESS,
    TRANSMISSIBILITY_LIMIT,
    TransferStiffnessResult,
    base_transmissibility,
    blocking_force_ratio,
    indirect_transfer_stiffness_result,
    loss_factor,
    transfer_stiffness_direct,
    transfer_stiffness_indirect,
    transfer_stiffness_level,
)

__all__ = [
    "FRF_UNITS",
    "REFERENCE_STIFFNESS",
    "TRANSMISSIBILITY_LIMIT",
    "JunctionTransmissionResult",
    "MobilityResult",
    "PowerInjectionResult",
    "RadiationEfficiencyResult",
    "RigidMassCalibrationResult",
    "TransferStiffnessResult",
    "angular_average_transmission_coefficient",
    "bar_modal_density",
    "base_transmissibility",
    "beam_bending_wave_speed",
    "beam_modal_density",
    "blocking_force_ratio",
    "coincidence_frequency",
    "convert_frf",
    "corner_transmission_coefficient",
    "coupling_loss_factor",
    "cylindrical_shell_modal_density",
    "flat_plate_modal_density",
    "indirect_transfer_stiffness_result",
    "infinite_beam_impedance",
    "infinite_beam_mobility",
    "infinite_beam_moment_mobility",
    "infinite_beam_point_mobility",
    "infinite_plate_impedance",
    "infinite_plate_mobility",
    "infinite_plate_point_mobility",
    "injected_power",
    "inline_transmission_coefficient",
    "junction_transmission",
    "junction_wave_parameters",
    "longitudinal_rod_impedance",
    "longitudinal_rod_mobility",
    "loss_factor",
    "plate_bending_stiffness",
    "plate_bending_wave_speed",
    "point_connection_coupling_loss_factor",
    "power_injection_clf",
    "power_injection_matrix",
    "radiation_efficiency",
    "random_error_percent",
    "resonance_frequency",
    "right_angle_transmission_coefficient",
    "rigid_mass_calibration_check",
    "ring_frequency",
    "sdof_accelerance",
    "sdof_mobility",
    "sdof_mobility_result",
    "sdof_receptance",
    "straight_transmission_coefficient",
    "transfer_stiffness_direct",
    "transfer_stiffness_indirect",
    "transfer_stiffness_level",
    "wave_vibration_reduction_index",
]
