#  Copyright (c) 2026. Jose Manuel Requena Plens
"""vibration.machinery subdomain of phonometry: machinery condition monitoring."""

from __future__ import annotations

from .diagnostics import (
    FaultFrequencyResult,
    FaultLine,
    bearing_fault_frequencies,
    blade_pass_frequencies,
    combine_fault_lines,
    gear_mesh_frequencies,
    induction_motor_frequencies,
    shaft_rate,
)
from .evaluation import (
    GEAR_ACCEPTANCE_HEADROOM,
    GEAR_DISPLACEMENT_CORNER_HZ,
    GEAR_DISPLACEMENT_SLOPE_DB_PER_DECADE,
    GEAR_UNIT_CLASSES,
    GEAR_UNIT_ZONES,
    GEAR_VELOCITY_CORNERS_HZ,
    GEAR_VELOCITY_SLOPE_DB_PER_DECADE,
    INDUSTRIAL_MACHINE_ZONES,
    OPERATIONAL_LIMIT_HEADROOM,
    SIGNIFICANT_CHANGE_FRACTION,
    TYPICAL_BOUNDARY_LADDER_MM_S,
    TYPICAL_ZONE_BOUNDARY_RANGES_MM_S,
    ZONE_LIMIT_FACTORS,
    GearUnitRatings,
    MachineZoneLimits,
    VectorChangeResult,
    ZoneBoundaries,
    alarm_limit,
    allowable_velocity,
    evaluation_zone,
    gear_housing_velocity_limit,
    gear_shaft_displacement_limit,
    gear_unit_zone_boundaries,
    industrial_machine_zone,
    is_significant_change,
    trip_limit,
    vibration_vector_change,
)

__all__ = [
    "FaultFrequencyResult",
    "FaultLine",
    "GEAR_ACCEPTANCE_HEADROOM",
    "GEAR_DISPLACEMENT_CORNER_HZ",
    "GEAR_DISPLACEMENT_SLOPE_DB_PER_DECADE",
    "GEAR_UNIT_CLASSES",
    "GEAR_UNIT_ZONES",
    "GEAR_VELOCITY_CORNERS_HZ",
    "GEAR_VELOCITY_SLOPE_DB_PER_DECADE",
    "GearUnitRatings",
    "INDUSTRIAL_MACHINE_ZONES",
    "MachineZoneLimits",
    "OPERATIONAL_LIMIT_HEADROOM",
    "SIGNIFICANT_CHANGE_FRACTION",
    "TYPICAL_BOUNDARY_LADDER_MM_S",
    "TYPICAL_ZONE_BOUNDARY_RANGES_MM_S",
    "VectorChangeResult",
    "ZONE_LIMIT_FACTORS",
    "ZoneBoundaries",
    "alarm_limit",
    "allowable_velocity",
    "bearing_fault_frequencies",
    "blade_pass_frequencies",
    "combine_fault_lines",
    "evaluation_zone",
    "gear_housing_velocity_limit",
    "gear_mesh_frequencies",
    "gear_shaft_displacement_limit",
    "gear_unit_zone_boundaries",
    "induction_motor_frequencies",
    "industrial_machine_zone",
    "is_significant_change",
    "shaft_rate",
    "trip_limit",
    "vibration_vector_change",
]
