#  Copyright (c) 2026. Jose Manuel Requena Plens
"""environment.assessment subdomain of phonometry: rating and assessment of environmental noise (ISO 1996, national codes)."""

from __future__ import annotations

from ..._compat import _namespace_dir, _namespace_shim
from .impulsive_sound import (
    ImpulseOnset,
    ImpulseProminenceResult,
    ImpulseProminenceWarning,
    ImpulsiveSoundResult,
    ImpulsiveSoundWarning,
    detect_onsets,
    impulse_adjustment,
    impulse_prominence,
    impulsive_sound_adjustment,
    predicted_prominence,
    rating_level,
    sound_pressure_level_history,
)
from .measurement import (
    EnvironmentalMeasurementWarning,
    RepeatedMeasurementResult,
    ResidualCorrectionResult,
    TonalAssessmentResult,
    assess_tonal_audibility,
    combined_standard_uncertainty,
    critical_bandwidth,
    expanded_uncertainty,
    gaussian_residual_level,
    residual_correction_uncertainty,
    residual_sound_correction,
    tonal_adjustment,
    tonal_adjustment_from_mean_audibility,
    tonal_audibility,
    tonal_seeking_survey,
    uncertainty_from_repeated_measurements,
)
from .rating import (
    composite_rating_level,
    lden,
    ldn,
)
from .spain import (
    ACOUSTIC_AREA_TYPES,
    RD1367_CORRECTION_VALUES,
    RD1367_EVALUATION_PERIODS,
    RD1367_MAX_CORRECTION,
    RD1367_PERIOD_CLOCK_LIMITS,
    RD1367_PERIOD_HOURS,
    ActivityAssessment,
    NoisePhase,
    PeriodAssessment,
    RegulationLimits,
    TonalCorrectionResult,
    activity_limits,
    adjacent_premises_limits,
    assess_activity,
    corrected_level,
    evaluation_period_level,
    impulsive_correction,
    indoor_quality_objectives,
    infrastructure_limits,
    long_term_corrected_level,
    low_frequency_correction,
    max_infrastructure_limit,
    outdoor_quality_objectives,
    round_reported_level,
    tonal_correction,
    total_correction,
    vibration_quality_objective,
)

__all__ = [
    "ACOUSTIC_AREA_TYPES",
    "RD1367_CORRECTION_VALUES",
    "RD1367_EVALUATION_PERIODS",
    "RD1367_MAX_CORRECTION",
    "RD1367_PERIOD_CLOCK_LIMITS",
    "RD1367_PERIOD_HOURS",
    "ActivityAssessment",
    "EnvironmentalMeasurementWarning",
    "ImpulseOnset",
    "ImpulseProminenceResult",
    "ImpulseProminenceWarning",
    "ImpulsiveSoundResult",
    "ImpulsiveSoundWarning",
    "NoisePhase",
    "PeriodAssessment",
    "RegulationLimits",
    "RepeatedMeasurementResult",
    "ResidualCorrectionResult",
    "TonalAssessmentResult",
    "TonalCorrectionResult",
    "activity_limits",
    "adjacent_premises_limits",
    "assess_activity",
    "assess_tonal_audibility",
    "combined_standard_uncertainty",
    "composite_rating_level",
    "corrected_level",
    "critical_bandwidth",
    "detect_onsets",
    "evaluation_period_level",
    "expanded_uncertainty",
    "gaussian_residual_level",
    "impulse_adjustment",
    "impulse_prominence",
    "impulsive_correction",
    "impulsive_sound_adjustment",
    "indoor_quality_objectives",
    "infrastructure_limits",
    "lden",
    "ldn",
    "long_term_corrected_level",
    "low_frequency_correction",
    "max_infrastructure_limit",
    "outdoor_quality_objectives",
    "predicted_prominence",
    "rating_level",
    "residual_correction_uncertainty",
    "residual_sound_correction",
    "round_reported_level",
    "sound_pressure_level_history",
    "tonal_adjustment",
    "tonal_adjustment_from_mean_audibility",
    "tonal_audibility",
    "tonal_correction",
    "tonal_seeking_survey",
    "total_correction",
    "uncertainty_from_repeated_measurements",
    "vibration_quality_objective",
]

#: No public name left this namespace in 4.0, but the modules did, so
#: ``assessment.impulse_prominence`` has to keep resolving to its alias module until 5.0: the
#: import registers it, the attribute read needs this.
__getattr__ = _namespace_shim(__name__)
__dir__ = _namespace_dir(__name__, __all__)
