#  Copyright (c) 2026. Jose Manuel Requena Plens
"""Deprecated location of the plot renderers (moved to ``phonometry._plot``).

Kept as a silent re-export for one deprecation cycle (removed in 4.0):
result ``.plot()`` call sites are being retargeted per domain during the
3.2 package reorganization, and external users of this private module keep
working unchanged."""

from __future__ import annotations

from ._plot.aircraft import (
    plot_aircraft_band_attenuation,
    plot_epnl,
    plot_flyover,
    plot_noise_contour,
    plot_npd_level,
    plot_rotorcraft_hemisphere,
)
from ._plot.building import (
    plot_airborne_insulation,
    plot_airborne_prediction,
    plot_band_uncertainty,
    plot_facade_insulation,
    plot_facade_prediction,
    plot_floor_covering_improvement,
    plot_impact_insulation,
    plot_impact_prediction,
    plot_impact_rating,
    plot_installed_structure_borne,
    plot_radiated_power,
    plot_structure_borne_power,
    plot_vibration_reduction,
    plot_weighted_rating,
)
from ._plot.electroacoustics import (
    plot_frequency_response,
    plot_harmonic_distortion,
)
from ._plot.emission import (
    plot_intensity,
    plot_sound_power,
    plot_vibration_sound_power,
)
from ._plot.environmental import (
    plot_impulse_prominence,
    plot_outdoor_attenuation,
    plot_tonal_adjustment,
    plot_wind_turbine_tonality,
)
from ._plot.hearing import (
    plot_age_threshold,
    plot_htlan,
    plot_nipts,
    plot_occupational_exposure,
    plot_sii,
    plot_sti,
)
from ._plot.materials import (
    plot_absorption_uncertainty,
    plot_diffusion_polar,
    plot_dynamic_stiffness,
    plot_impedance_tube,
    plot_insitu_absorption,
    plot_scattering_coefficient,
    plot_static_airflow,
    plot_weighted_absorption,
)
from ._plot.metrology import (
    plot_monte_carlo,
    plot_uncertainty_budget,
)
from ._plot.psychoacoustics import (
    plot_ecma_loudness,
    plot_ecma_roughness,
    plot_ecma_tonality,
    plot_fluctuation_strength,
    plot_moore_glasberg_loudness,
    plot_moore_glasberg_time_loudness,
    plot_psychoacoustic_annoyance,
    plot_tone_audibility,
    plot_zwicker_loudness,
)
from ._plot.room import (
    plot_decay_curve,
    plot_enclosed_space_absorption,
    plot_excitation,
    plot_impulse_response,
    plot_noise_criterion,
    plot_open_plan,
    plot_reverberation_models,
    plot_room_acoustics,
    plot_room_criterion,
)
from ._plot.simulation import (
    plot_fdtd_probes,
    plot_fdtd_snapshot,
)
from ._plot.underwater import (
    plot_ambient_noise,
    plot_bottom_loss,
    plot_normal_modes,
    plot_parabolic_equation,
    plot_pile_strike,
    plot_ray_trace,
    plot_ship_source_level,
    plot_ship_traffic_spectrum,
    plot_sonar_equation,
    plot_sound_speed_profile,
    plot_transmission_loss,
)
from ._plot.vibration import (
    plot_daily_exposure,
    plot_mobility,
    plot_multiple_shock,
    plot_transfer_stiffness,
    plot_vibration_weighting,
    plot_weighted_spectrum,
)

__all__ = [
    "plot_absorption_uncertainty",
    "plot_age_threshold",
    "plot_airborne_insulation",
    "plot_airborne_prediction",
    "plot_aircraft_band_attenuation",
    "plot_ambient_noise",
    "plot_band_uncertainty",
    "plot_bottom_loss",
    "plot_daily_exposure",
    "plot_decay_curve",
    "plot_diffusion_polar",
    "plot_dynamic_stiffness",
    "plot_ecma_loudness",
    "plot_ecma_roughness",
    "plot_ecma_tonality",
    "plot_enclosed_space_absorption",
    "plot_epnl",
    "plot_excitation",
    "plot_facade_insulation",
    "plot_facade_prediction",
    "plot_fdtd_probes",
    "plot_fdtd_snapshot",
    "plot_floor_covering_improvement",
    "plot_fluctuation_strength",
    "plot_flyover",
    "plot_frequency_response",
    "plot_harmonic_distortion",
    "plot_htlan",
    "plot_impact_insulation",
    "plot_impact_prediction",
    "plot_impact_rating",
    "plot_impedance_tube",
    "plot_impulse_prominence",
    "plot_impulse_response",
    "plot_insitu_absorption",
    "plot_installed_structure_borne",
    "plot_intensity",
    "plot_mobility",
    "plot_monte_carlo",
    "plot_moore_glasberg_loudness",
    "plot_moore_glasberg_time_loudness",
    "plot_multiple_shock",
    "plot_nipts",
    "plot_noise_contour",
    "plot_noise_criterion",
    "plot_normal_modes",
    "plot_npd_level",
    "plot_occupational_exposure",
    "plot_open_plan",
    "plot_outdoor_attenuation",
    "plot_parabolic_equation",
    "plot_pile_strike",
    "plot_psychoacoustic_annoyance",
    "plot_radiated_power",
    "plot_ray_trace",
    "plot_reverberation_models",
    "plot_room_acoustics",
    "plot_room_criterion",
    "plot_rotorcraft_hemisphere",
    "plot_scattering_coefficient",
    "plot_ship_source_level",
    "plot_ship_traffic_spectrum",
    "plot_sii",
    "plot_sonar_equation",
    "plot_sound_power",
    "plot_sound_speed_profile",
    "plot_static_airflow",
    "plot_sti",
    "plot_structure_borne_power",
    "plot_tonal_adjustment",
    "plot_tone_audibility",
    "plot_transfer_stiffness",
    "plot_transmission_loss",
    "plot_uncertainty_budget",
    "plot_vibration_reduction",
    "plot_vibration_sound_power",
    "plot_vibration_weighting",
    "plot_weighted_absorption",
    "plot_weighted_rating",
    "plot_weighted_spectrum",
    "plot_wind_turbine_tonality",
    "plot_zwicker_loudness",
]
