#  Copyright (c) 2026. Jose Manuel Requena Plens
"""aircraft domain of phonometry (see module docstrings)."""

from __future__ import annotations

from .airport_noise import (
    AerodromeAtmosphere,
    FlightSegmentState,
    FlyoverResult,
    NoiseContourResult,
    NpdLevelResult,
    duration_correction,
    engine_installation_correction,
    event_level,
    impedance_adjustment,
    lateral_attenuation,
    noise_contour,
    noise_fraction,
    npd_curve,
    npd_level,
    start_of_roll_directivity,
)
from .anp_fleet import (
    AnpAircraft,
    AnpDatabase,
    AnpNpdCurves,
    AnpProfile,
    load_anp_database,
)
from .atmospheric_absorption import AircraftBandAttenuation, sae_band_attenuation
from .certification import (
    NOY_BANDS,
    EPNLResult,
    effective_perceived_noise_level,
    epnl_from_pnlt,
    perceived_noise_level,
    perceived_noisiness,
    tone_correction,
)
from .flight_performance import (
    Aerodrome,
    AerodynamicCoefficients,
    ApproachStep,
    DepartureStep,
    FlightProfile,
    JetEngineCoefficients,
    PerformanceAircraft,
    ProfilePoint,
    PropellerEngineCoefficients,
    approach_profile,
    departure_profile,
)
from .measurement_system import verify_aircraft_noise_system
from .rotorcraft_noise import (
    FlightConditionInterpolation,
    FlightPathKinematics,
    RotorcraftAtmosphere,
    RotorcraftEventResult,
    RotorcraftGround,
    RotorcraftHemisphere,
    RotorcraftNoiseContourResult,
    RotorcraftTrackState,
    flight_condition_weights,
    flight_path_kinematics,
    hemisphere_source_level,
    hover_derived_hemisphere,
    hover_ring_hemisphere,
    interpolated_source_level,
    rotorcraft_event_level,
    rotorcraft_noise_contour,
)
from .rotorcraft_propagation import (
    MeanGroundPlaneResult,
    TerrainScreeningResult,
    atmospheric_adjustment,
    diffraction_attenuation,
    ground_effect_adjustment,
    mean_flow_resistivity,
    mean_ground_plane,
    spherical_spreading_adjustment,
    terrain_screening_adjustment,
)

__all__ = [
    "NOY_BANDS",
    "Aerodrome",
    "AerodromeAtmosphere",
    "AerodynamicCoefficients",
    "AircraftBandAttenuation",
    "AnpAircraft",
    "AnpDatabase",
    "AnpNpdCurves",
    "AnpProfile",
    "ApproachStep",
    "DepartureStep",
    "EPNLResult",
    "FlightConditionInterpolation",
    "FlightPathKinematics",
    "FlightProfile",
    "FlightSegmentState",
    "FlyoverResult",
    "JetEngineCoefficients",
    "MeanGroundPlaneResult",
    "NoiseContourResult",
    "NpdLevelResult",
    "PerformanceAircraft",
    "ProfilePoint",
    "PropellerEngineCoefficients",
    "RotorcraftAtmosphere",
    "RotorcraftEventResult",
    "RotorcraftGround",
    "RotorcraftHemisphere",
    "RotorcraftNoiseContourResult",
    "RotorcraftTrackState",
    "TerrainScreeningResult",
    "approach_profile",
    "atmospheric_adjustment",
    "departure_profile",
    "diffraction_attenuation",
    "duration_correction",
    "effective_perceived_noise_level",
    "engine_installation_correction",
    "epnl_from_pnlt",
    "event_level",
    "flight_condition_weights",
    "flight_path_kinematics",
    "ground_effect_adjustment",
    "hemisphere_source_level",
    "hover_derived_hemisphere",
    "hover_ring_hemisphere",
    "impedance_adjustment",
    "interpolated_source_level",
    "lateral_attenuation",
    "load_anp_database",
    "mean_flow_resistivity",
    "mean_ground_plane",
    "noise_contour",
    "noise_fraction",
    "npd_curve",
    "npd_level",
    "perceived_noise_level",
    "perceived_noisiness",
    "rotorcraft_event_level",
    "rotorcraft_noise_contour",
    "sae_band_attenuation",
    "spherical_spreading_adjustment",
    "start_of_roll_directivity",
    "terrain_screening_adjustment",
    "tone_correction",
    "verify_aircraft_noise_system",
]
