#  Copyright (c) 2026. Jose Manuel Requena Plens
"""vibration domain of phonometry (see module docstrings).

Three families since 4.0, by who reads them: :mod:`~phonometry.vibration.structural`
is the structural acoustics that feeds building prediction (mobility, junctions,
radiation, SEA), :mod:`~phonometry.vibration.human` is exposure of people
(ISO 2631, ISO 5349) and :mod:`~phonometry.vibration.machinery` is condition
monitoring. Every public name is still exported here, so
``from phonometry import vibration`` reads exactly as it did.
"""

from __future__ import annotations

from .._compat import _namespace_dir, _namespace_shim
from .._plot.geometry import (
    plot_plate_geometry,
)
from .human import (
    HAV_EAV_A8,
    HAV_ELV_A8,
    REFERENCE_ACCELERATION,
    REFERENCE_DURATION_S,
    WBV_EAV_A8,
    WBV_EAV_VDV,
    WBV_ELV_A8,
    WBV_ELV_VDV,
    WEIGHTING_NAMES,
    DailyVibrationExposure,
    ExposureAssessment,
    HumanVibrationWarning,
    MultipleShockResult,
    WeightedSpectrum,
    WeightingResponse,
    acceleration_dose,
    apply_weighting,
    combine_partial_exposures,
    compression_dose,
    crest_factor,
    daily_dose,
    daily_dose_multi,
    daily_exposure,
    daily_vibration_exposure,
    dose_from_peaks,
    energy_equivalent_acceleration,
    exposure_assessment,
    frequency_weighting,
    hav_daily_exposure,
    hav_vwf_lifetime_years,
    injury_probability,
    injury_risk,
    motion_sickness_dose_value,
    mtvv,
    multiple_shock_assessment,
    partial_exposure,
    response_peaks,
    running_rms,
    seat_to_spine_transfer,
    spinal_response,
    static_stress,
    ultimate_strength,
    vibration_dose_value,
    vibration_total_value,
    wbv_exposure_basis,
    weighted_acceleration,
    weighting_factors,
)
from .machinery import (
    FaultFrequencyResult,
    FaultLine,
    bearing_fault_frequencies,
    blade_pass_frequencies,
    combine_fault_lines,
    gear_mesh_frequencies,
    induction_motor_frequencies,
    shaft_rate,
)
from .structural import (
    FRF_UNITS,
    REFERENCE_STIFFNESS,
    TRANSMISSIBILITY_LIMIT,
    JunctionTransmissionResult,
    MobilityResult,
    PowerInjectionResult,
    RadiationEfficiencyResult,
    RigidMassCalibrationResult,
    TransferStiffnessResult,
    angular_average_transmission_coefficient,
    bar_modal_density,
    base_transmissibility,
    beam_bending_wave_speed,
    beam_modal_density,
    blocking_force_ratio,
    coincidence_frequency,
    convert_frf,
    corner_transmission_coefficient,
    coupling_loss_factor,
    cylindrical_shell_modal_density,
    flat_plate_modal_density,
    indirect_transfer_stiffness_result,
    infinite_beam_impedance,
    infinite_beam_mobility,
    infinite_beam_moment_mobility,
    infinite_beam_point_mobility,
    infinite_plate_impedance,
    infinite_plate_mobility,
    infinite_plate_point_mobility,
    injected_power,
    inline_transmission_coefficient,
    junction_transmission,
    junction_wave_parameters,
    longitudinal_rod_impedance,
    longitudinal_rod_mobility,
    loss_factor,
    plate_bending_stiffness,
    plate_bending_wave_speed,
    point_connection_coupling_loss_factor,
    power_injection_clf,
    power_injection_matrix,
    radiation_efficiency,
    random_error_percent,
    resonance_frequency,
    right_angle_transmission_coefficient,
    rigid_mass_calibration_check,
    ring_frequency,
    sdof_accelerance,
    sdof_mobility,
    sdof_mobility_result,
    sdof_receptance,
    straight_transmission_coefficient,
    transfer_stiffness_direct,
    transfer_stiffness_indirect,
    transfer_stiffness_level,
    wave_vibration_reduction_index,
)

__all__ = [
    "FRF_UNITS",
    "HAV_EAV_A8",
    "HAV_ELV_A8",
    "REFERENCE_ACCELERATION",
    "REFERENCE_DURATION_S",
    "REFERENCE_STIFFNESS",
    "TRANSMISSIBILITY_LIMIT",
    "WBV_EAV_A8",
    "WBV_EAV_VDV",
    "WBV_ELV_A8",
    "WBV_ELV_VDV",
    "WEIGHTING_NAMES",
    "DailyVibrationExposure",
    "ExposureAssessment",
    "FaultFrequencyResult",
    "FaultLine",
    "HumanVibrationWarning",
    "JunctionTransmissionResult",
    "MobilityResult",
    "MultipleShockResult",
    "PowerInjectionResult",
    "RadiationEfficiencyResult",
    "RigidMassCalibrationResult",
    "TransferStiffnessResult",
    "WeightedSpectrum",
    "WeightingResponse",
    "acceleration_dose",
    "angular_average_transmission_coefficient",
    "apply_weighting",
    "bar_modal_density",
    "base_transmissibility",
    "beam_bending_wave_speed",
    "beam_modal_density",
    "bearing_fault_frequencies",
    "blade_pass_frequencies",
    "blocking_force_ratio",
    "coincidence_frequency",
    "combine_fault_lines",
    "combine_partial_exposures",
    "compression_dose",
    "convert_frf",
    "corner_transmission_coefficient",
    "coupling_loss_factor",
    "crest_factor",
    "cylindrical_shell_modal_density",
    "daily_dose",
    "daily_dose_multi",
    "daily_exposure",
    "daily_vibration_exposure",
    "dose_from_peaks",
    "energy_equivalent_acceleration",
    "exposure_assessment",
    "flat_plate_modal_density",
    "frequency_weighting",
    "gear_mesh_frequencies",
    "hav_daily_exposure",
    "hav_vwf_lifetime_years",
    "indirect_transfer_stiffness_result",
    "induction_motor_frequencies",
    "infinite_beam_impedance",
    "infinite_beam_mobility",
    "infinite_beam_moment_mobility",
    "infinite_beam_point_mobility",
    "infinite_plate_impedance",
    "infinite_plate_mobility",
    "infinite_plate_point_mobility",
    "injected_power",
    "injury_probability",
    "injury_risk",
    "inline_transmission_coefficient",
    "junction_transmission",
    "junction_wave_parameters",
    "longitudinal_rod_impedance",
    "longitudinal_rod_mobility",
    "loss_factor",
    "motion_sickness_dose_value",
    "mtvv",
    "multiple_shock_assessment",
    "partial_exposure",
    "plate_bending_stiffness",
    "plate_bending_wave_speed",
    "plot_plate_geometry",
    "point_connection_coupling_loss_factor",
    "power_injection_clf",
    "power_injection_matrix",
    "radiation_efficiency",
    "random_error_percent",
    "resonance_frequency",
    "response_peaks",
    "right_angle_transmission_coefficient",
    "rigid_mass_calibration_check",
    "ring_frequency",
    "running_rms",
    "sdof_accelerance",
    "sdof_mobility",
    "sdof_mobility_result",
    "sdof_receptance",
    "seat_to_spine_transfer",
    "shaft_rate",
    "spinal_response",
    "static_stress",
    "straight_transmission_coefficient",
    "transfer_stiffness_direct",
    "transfer_stiffness_indirect",
    "transfer_stiffness_level",
    "ultimate_strength",
    "vibration_dose_value",
    "vibration_total_value",
    "wave_vibration_reduction_index",
    "wbv_exposure_basis",
    "weighted_acceleration",
    "weighting_factors",
]

#: No public name left this namespace in 4.0, but the modules did, so
#: ``vibration.human_vibration`` has to keep resolving to its alias module
#: until 5.0: the import registers it, the attribute read needs this.
__getattr__ = _namespace_shim(__name__)
__dir__ = _namespace_dir(__name__, __all__)
