#  Copyright (c) 2026. Jose M. Requena-Plens
"""Guard against stale conformance counts in the prose.

``docs/CONFORMANCE.md`` is generated by :mod:`scripts.conformance_report` and
its header line is the single authority for how many checks the suite runs,
across how many domains, against how many standards. Pages that quote those
integers used to type them out, and three of them fell a release behind: the
landing page said 427 checks while *Why phonometry* still said 371.

The site now imports the numbers from ``site/src/data/conformance-stats.mjs``,
so the Astro pages cannot drift. The plain-markdown mirror under ``docs/`` has
no build step to interpolate through, so this check covers it: any sentence in
the corpus that states a conformance count must state the current one.

Run with ``python scripts/check_conformance_claims.py``; CI runs it alongside
the conformance regeneration gate.
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPORT = ROOT / "docs" / "CONFORMANCE.md"

#: The generated headline the counts are read from.
HEADLINE = re.compile(
    r"\*\*(?P<passing>\d+)\s*/\s*(?P<total>\d+)\s+conformance checks pass\*\*\s+"
    r"across\s+(?P<domains>\d+)\s+domains\s+and\s+(?P<standards>\d+)\s+standards"
)

#: Prose patterns that assert a count. Each captures the number in group 1 and
#: names the report field it must equal. Both languages, since the Spanish
#: mirror carries the same claims.
#:
#: Every pattern is anchored to conformance wording. A bare "N standards" would
#: match any sentence in the corpus that happens to count standards for an
#: unrelated reason, so the domain and standard counts are only read where they
#: appear in the report's own "across N domains and N standards" phrasing.
CLAIMS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"(\d+)\s+(?:numerical\s+)?conformance checks"), "total"),
    (re.compile(r"\ball\s+(\d+)\s+checks\b"), "total"),
    (re.compile(r"(\d+)\s+comprobaciones(?:\s+numéricas)?\s+de conformidad"), "total"),
    (re.compile(r"\blas\s+(\d+)\s+comprobaciones\b"), "total"),
    (re.compile(r"across\s+(\d+)\s+domains\s+and\s+\d+\s+standards"), "domains"),
    (re.compile(r"across\s+\d+\s+domains\s+and\s+(\d+)\s+standards"), "standards"),
    (re.compile(r"en\s+(\d+)\s+dominios\s+y\s+\d+\s+normas"), "domains"),
    (re.compile(r"en\s+\d+\s+dominios\s+y\s+(\d+)\s+normas"), "standards"),
    # The landing-page meta descriptions. Starlight frontmatter is static and
    # cannot interpolate, so these two strings stay written out and this check
    # is the only thing keeping them honest.
    (re.compile(r"conformance checks against\s+(\d+)\b"), "standards"),
    (re.compile(r"comprobaciones de conformidad frente a\s+(\d+)\b"), "standards"),
)

#: Files whose counts are generated or quoted from a fixed historical context.
EXCLUDED = {
    REPORT,
    ROOT / "CHANGELOG.md",
    ROOT / "docs" / "ERRATA.md",
}

#: Directory names that never ship: local working notes, build output, vendored
#: dependencies. `docs/superpowers/` in particular is gitignored scratch space.
EXCLUDED_DIRS = frozenset({"superpowers", "node_modules", "dist", ".astro"})


def _expected() -> dict[str, int]:
    """Parse the authoritative counts out of the generated report."""
    match = HEADLINE.search(REPORT.read_text(encoding="utf8"))
    if match is None:
        sys.exit(
            f"{REPORT.relative_to(ROOT)}: headline not found. The report format "
            "changed; update HEADLINE here and in "
            "site/src/data/conformance-stats.mjs."
        )
    return {name: int(value) for name, value in match.groupdict().items()}


def _sources() -> list[pathlib.Path]:
    """Every prose file that could quote a count."""
    roots = (ROOT / "docs", ROOT / "site" / "src" / "content" / "docs")
    found: list[pathlib.Path] = []
    for root in roots:
        if not root.is_dir():
            continue
        for pattern in ("*.md", "*.mdx"):
            found += sorted(root.rglob(pattern))
    return [
        path
        for path in found
        if path not in EXCLUDED and EXCLUDED_DIRS.isdisjoint(path.parts)
    ]


def main() -> int:
    expected = _expected()
    problems: list[str] = []

    for path in _sources():
        for lineno, line in enumerate(
            path.read_text(encoding="utf8").splitlines(), start=1
        ):
            for pattern, field in CLAIMS:
                for match in pattern.finditer(line):
                    claimed = int(match.group(1))
                    if claimed != expected[field]:
                        problems.append(
                            f"{path.relative_to(ROOT)}:{lineno}: claims "
                            f"{claimed} {field}, report says {expected[field]} "
                            f"-> {match.group(0)!r}"
                        )

    if problems:
        print(
            "Stale conformance counts. docs/CONFORMANCE.md is the authority; "
            "regenerate it with `make conformance` if it is behind, otherwise "
            "fix the prose (Astro pages should import from "
            "site/src/data/conformance-stats.mjs rather than hardcode):\n",
            file=sys.stderr,
        )
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    print(
        f"Conformance claims consistent: {expected['total']} checks, "
        f"{expected['domains']} domains, {expected['standards']} standards."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
