#  Copyright (c) 2026. Jose Manuel Requena Plens
"""Keep the conformance counts quoted in the prose equal to the report's.

``docs/conformance.json`` is generated by :mod:`scripts.conformance_report` and
its ``counts`` object is the single authority for how many checks the suite
runs, across how many domains, against how many standards. Pages that quote
those integers used to type them out, and three of them fell a release behind:
the landing page said 427 checks while *Why phonometry* still said 371.

This script used to read them by matching a regular expression against the
report's headline sentence, which made an English sentence a wire format:
three files parsed it, in two languages, and each carried an error message
telling you to go and update the other two. Reading a field out of a document
that exists to be read is what replaced that.

The Astro page bodies import the numbers from
``site/src/data/conformance-stats.mjs``, so they cannot drift. What is left is
the text that has no build step to interpolate through: the plain-markdown
mirror under ``docs/``, the ``README.md`` and generated ``README_PYPI.md`` at
the repository root, the ``.zenodo.json`` description, and the YAML
frontmatter of the site pages (the landing-page meta descriptions and the
JSON-LD blocks on the conformance pages, which are static data parsed before
MDX ever runs). Those used to be edited by hand after every change that moved
a count.

The READMEs are why the file set reaches the repository root at all, instead
of stopping at ``docs/``. They sat outside it, said "more than 250 standards"
while the report said 365, and the gate called the corpus consistent
throughout. The PyPI one is the worse of the two to get wrong: PyPI freezes a
long description at upload, so a count that is stale on release day stays
published.

This script owns them instead. It has two modes over **one** list of patterns,
so the two can never disagree:

* the default read-only check, which reports every stale count and exits
  non-zero. This is the CI gate;
* ``--write`` (``--fix``), which substitutes the authoritative value in place.
  It replaces the span of the captured digits and nothing else, so the
  surrounding prose, and any other number that happens to share the value,
  are left untouched. ``make conformance`` runs it right after regenerating
  the report.

Run with ``python scripts/check_conformance_claims.py``; CI runs it alongside
the conformance regeneration gate.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import pathlib
import re
import sys
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Mapping, Sequence

ROOT = pathlib.Path(__file__).resolve().parent.parent

#: Names of the ``counts`` fields the prose is allowed to quote, mapped to what
#: this script calls them. ``total`` is the historical name for the number of
#: checks and is kept because it is what the :data:`CLAIMS` table says.
FIELDS = {
    "checks": "total",
    "passing": "passing",
    "domains": "domains",
    "standards": "standards",
    "designations": "designations",
    "sources": "sources",
}

#: Prose patterns that assert a count. Each captures the number in group 1 and
#: names the report field it must equal. Both languages, since the Spanish
#: mirror carries the same claims.
#:
#: This tuple is the whole map of where the numbers live: the check reads it to
#: find stale values and the writer reads it to fix them, from the same entry,
#: with the same span. Adding a place a count is quoted means adding a pattern
#: here and nothing else.
#:
#: Every pattern is anchored to conformance wording. A bare "N standards" would
#: match any sentence in the corpus that happens to count standards for an
#: unrelated reason, so the domain and standard counts are only read where they
#: appear in the report's own "across N domains and N standards" phrasing.
CLAIMS: tuple[tuple[re.Pattern[str], str], ...] = (
    (re.compile(r"(\d+)\s+(?:numerical\s+)?conformance checks"), "total"),
    (re.compile(r"\ball\s+(\d+)\s+checks\b"), "total"),
    (re.compile(r"(\d+)\s+comprobaciones(?:\s+numéricas)?\s+de conformidad"), "total"),
    (re.compile(r"\blas\s+(\d+)\s+comprobaciones\b"), "total"),
    (re.compile(r"across\s+(\d+)\s+domains\s+and\s+\d+\s+standards"), "domains"),
    (re.compile(r"across\s+\d+\s+domains\s+and\s+(\d+)\s+standards"), "standards"),
    (re.compile(r"en\s+(\d+)\s+dominios\s+y\s+\d+\s+normas"), "domains"),
    (re.compile(r"en\s+\d+\s+dominios\s+y\s+(\d+)\s+normas"), "standards"),
    # The landing-page meta descriptions. Starlight frontmatter is static YAML,
    # parsed before MDX compiles, so it cannot interpolate an import; the
    # writer keeps these two strings current instead.
    (re.compile(r"conformance checks against\s+(\d+)\b"), "standards"),
    (re.compile(r"comprobaciones de conformidad frente a\s+(\d+)\b"), "standards"),
    (re.compile(r"across\s+(\d+)\s+domains\s+against\s+\d+\s+"), "domains"),
    (re.compile(r"across\s+\d+\s+domains\s+against\s+(\d+)\s+"), "standards"),
    # The honest split the reference parser makes available: distinct normative
    # documents, and distinct further works. No page states either yet - what
    # is published is the citation-group count, and changing a published claim
    # is a decision, not a refactor - so these two patterns police wording that
    # does not exist here today and will the moment it is written.
    (re.compile(r"(\d+)\s+normative designations\b"), "designations"),
    (re.compile(r"(\d+)\s+further published sources\b"), "sources"),
    (re.compile(r"(\d+)\s+designaciones normativas\b"), "designations"),
    (re.compile(r"(\d+)\s+fuentes publicadas adicionales\b"), "sources"),
)

#: Files whose counts are generated or quoted from a fixed historical context.
EXCLUDED_NAMES = (
    ("docs", "CONFORMANCE.md"),
    ("docs", "conformance.json"),
    ("CHANGELOG.md",),
    ("docs", "ERRATA.md"),
)

#: Directory names that never ship: local working notes, build output, vendored
#: dependencies. `docs/superpowers/` in particular is gitignored scratch space.
EXCLUDED_DIRS = frozenset({"superpowers", "node_modules", "dist", ".astro"})


@dataclasses.dataclass(frozen=True)
class Claim:
    """One quoted count, located precisely enough to rewrite it.

    :param field: Report field the number must equal (``total``, ``domains``
        or ``standards``).
    :param claimed: The integer the prose states.
    :param start: Offset of the first digit within its line.
    :param end: Offset one past the last digit within its line.
    :param phrase: The whole matched phrase, for the diagnostic message.
    """

    field: str
    claimed: int
    start: int
    end: int
    phrase: str


def report_path(root: pathlib.Path = ROOT) -> pathlib.Path:
    """Path of the generated document that holds the authoritative counts."""
    return root / "docs" / "conformance.json"


def expected_counts(root: pathlib.Path = ROOT) -> dict[str, int]:
    """Read the authoritative counts out of the generated artefact.

    :param root: Repository root to read the artefact from.
    :return: Mapping of the names :data:`CLAIMS` uses to their values.
    :raises ValueError: If the artefact is missing, unreadable, or no longer
        carries one of the fields the claims are checked against.
    """
    report = report_path(root)
    try:
        counts = json.loads(_read(report))["counts"]
    except (OSError, ValueError, KeyError) as error:
        msg = (
            f"{_label(report, root)}: cannot read the conformance counts "
            f"({error}). Regenerate the artefact with `make conformance`."
        )
        raise ValueError(msg) from error
    missing = sorted(set(FIELDS) - set(counts))
    if missing:
        msg = (
            f"{_label(report, root)}: counts is missing {', '.join(missing)}. "
            "The artefact schema changed; update FIELDS here."
        )
        raise ValueError(msg)
    return {name: int(counts[field]) for field, name in FIELDS.items()}


def sources(root: pathlib.Path = ROOT) -> list[pathlib.Path]:
    """Every prose file that could quote a count.

    Three places, for three reasons.

    The guides and their site mirrors, walked from ``docs/`` and
    ``site/src/content/docs/``.

    The markdown at the repository root, non-recursively. This is where the
    two most-read pages of prose in the project live, and they were outside
    the walk: ``README.md``, and the ``README_PYPI.md`` generated from it,
    whose text is the PyPI long description. That one matters most of all,
    because PyPI freezes a description at upload, so a count that is stale
    when the release goes out is published wrong for good. The glob is
    deliberately not ``rglob``: recursing from the root would pull in
    ``stub/``, ``site/`` and every vendored tree under them.

    ``.zenodo.json``, because its description is prose too: it is the text the
    archived record shows, it states the counts, and it has no build step to
    interpolate them through.

    :param root: Repository root to walk.
    :return: The files to check or rewrite, in a stable order.
    """
    excluded = {root.joinpath(*parts) for parts in EXCLUDED_NAMES}
    roots = (root / "docs", root / "site" / "src" / "content" / "docs")
    found: list[pathlib.Path] = []
    for base in roots:
        if not base.is_dir():
            continue
        for pattern in ("*.md", "*.mdx"):
            found += sorted(base.rglob(pattern))
    found += sorted(root.glob("*.md"))
    kept = [
        path
        for path in found
        if path not in excluded and EXCLUDED_DIRS.isdisjoint(path.parts)
    ]
    zenodo = root / ".zenodo.json"
    if zenodo.is_file():
        kept.append(zenodo)
    return kept


def claims_in(line: str) -> list[Claim]:
    """Every count asserted by one line of prose.

    Patterns overlap by design (the same phrase yields a domain claim and a
    standard claim), so the same digits can be reported by more than one
    pattern. Identical spans are collapsed here; a span claimed for two
    different fields would make the map ambiguous and is rejected.

    :param line: A single line, without its line ending.
    :return: The claims found, ordered by position.
    :raises ValueError: If two patterns disagree about what a number means.
    """
    seen: dict[tuple[int, int], Claim] = {}
    for pattern, field in CLAIMS:
        for match in pattern.finditer(line):
            start, end = match.span(1)
            claim = Claim(field, int(match.group(1)), start, end, match.group(0))
            previous = seen.get((start, end))
            if previous is None:
                seen[(start, end)] = claim
            elif previous.field != field:
                msg = (
                    f"ambiguous conformance claim {line[start:end]!r}: "
                    f"read as {previous.field!r} by {previous.phrase!r} and as "
                    f"{field!r} by {match.group(0)!r}. Tighten one of the "
                    "patterns in CLAIMS."
                )
                raise ValueError(msg)
    return [seen[key] for key in sorted(seen)]


def rewrite_line(line: str, expected: Mapping[str, int]) -> tuple[str, list[Claim]]:
    """Set every count asserted by a line to its authoritative value.

    The substitution uses the span of the captured digits, never a textual
    replace: a blind ``str.replace`` of one integer for another rewrites every
    other number in the line that happens to share the value.

    :param line: A single line, with or without its line ending.
    :param expected: The authoritative counts.
    :return: The corrected line and the claims that had to be corrected.
    """
    ending_at = len(line.rstrip("\r\n"))
    body, ending = line[:ending_at], line[ending_at:]

    stale = [c for c in claims_in(body) if c.claimed != expected[c.field]]
    reach = len(body)
    for claim in reversed(stale):
        if claim.end > reach:
            msg = (
                f"overlapping conformance claims in {body!r}; the writer cannot "
                "rewrite spans that intersect."
            )
            raise ValueError(msg)
        reach = claim.start
        body = body[: claim.start] + str(expected[claim.field]) + body[claim.end :]
    return body + ending, stale


def rewrite_text(
    text: str, expected: Mapping[str, int]
) -> tuple[str, list[tuple[int, Claim]]]:
    """Apply :func:`rewrite_line` to a whole file, line endings preserved.

    :param text: The file's contents.
    :param expected: The authoritative counts.
    :return: The corrected text and the ``(line number, claim)`` pairs fixed.
    """
    out: list[str] = []
    fixed: list[tuple[int, Claim]] = []
    for lineno, line in enumerate(text.splitlines(keepends=True), start=1):
        corrected, stale = rewrite_line(line, expected)
        out.append(corrected)
        fixed += [(lineno, claim) for claim in stale]
    return "".join(out), fixed


def _read(path: pathlib.Path) -> str:
    """Read a file with its line endings left exactly as they are on disk."""
    return path.read_text(encoding="utf8", newline="")


def _label(path: pathlib.Path, root: pathlib.Path) -> str:
    """Repo-relative path in a form that reads the same on every platform."""
    return path.relative_to(root).as_posix()


def describe(label: str, lineno: int, claim: Claim, value: int) -> str:
    """One line of diagnostics about a stale claim."""
    return (
        f"{label}:{lineno}: claims {claim.claimed} {claim.field}, report says "
        f"{value} -> {claim.phrase!r}"
    )


def check(root: pathlib.Path, expected: Mapping[str, int]) -> list[str]:
    """Every stale count in the corpus, as printable diagnostics."""
    problems: list[str] = []
    for path in sources(root):
        _, fixed = rewrite_text(_read(path), expected)
        problems += [
            describe(_label(path, root), lineno, claim, expected[claim.field])
            for lineno, claim in fixed
        ]
    return problems


def write(root: pathlib.Path, expected: Mapping[str, int]) -> list[str]:
    """Bring every quoted count into line with the report.

    :param root: Repository root to rewrite in place.
    :param expected: The authoritative counts.
    :return: A printable description of each substitution made.
    """
    changes: list[str] = []
    for path in sources(root):
        text = _read(path)
        corrected, fixed = rewrite_text(text, expected)
        if not fixed:
            continue
        # `newline=""` on both ends: the file keeps whatever line endings it
        # already had, so a rewrite is a change of digits and nothing else.
        path.write_text(corrected, encoding="utf8", newline="")
        changes += [
            f"{_label(path, root)}:{lineno}: {claim.claimed} -> "
            f"{expected[claim.field]} {claim.field} in {claim.phrase!r}"
            for lineno, claim in fixed
        ]
    return changes


def main(argv: Sequence[str] | None = None) -> int:
    """Check, or with ``--write`` correct, the counts quoted in the prose."""
    parser = argparse.ArgumentParser(
        description=(
            "Check that every conformance count quoted in the docs, the root "
            "READMEs, the site frontmatter and .zenodo.json equals the "
            "counts recorded in docs/conformance.json."
        )
    )
    parser.add_argument(
        "--write",
        "--fix",
        action="store_true",
        help=(
            "rewrite the quoted counts in place instead of only reporting "
            "them. Only the digits of a matched claim are replaced."
        ),
    )
    parser.add_argument(
        "--root",
        type=pathlib.Path,
        default=ROOT,
        help="repository root to operate on (default: this checkout)",
    )
    args = parser.parse_args(argv)
    root: pathlib.Path = args.root.resolve()

    # Every failure that means "the CLAIMS table or the report format needs
    # attention" surfaces as a ValueError: a report whose headline no longer
    # parses, a number two patterns read differently, spans that intersect.
    # They are all editing mistakes, so they get the same one-line diagnostic
    # rather than a traceback.
    try:
        return _run(args.write, root)
    except ValueError as error:
        print(error, file=sys.stderr)
        return 1


def _run(writing: bool, root: pathlib.Path) -> int:
    """Body of :func:`main`, once the arguments are settled."""
    expected = expected_counts(root)
    summary = (
        f"{expected['total']} checks, {expected['domains']} domains, "
        f"{expected['standards']} standards ({expected['designations']} normative "
        f"designations, {expected['sources']} further sources)"
    )

    if writing:
        changes = write(root, expected)
        for change in changes:
            print(f"  {change}")
        remaining = check(root, expected)
        if remaining:
            print(
                "Counts still stale after rewriting. A claim was matched but "
                "could not be corrected:\n",
                file=sys.stderr,
            )
            for problem in remaining:
                print(f"  {problem}", file=sys.stderr)
            return 1
        if changes:
            print(f"Rewrote {len(changes)} conformance count(s) from ", end="")
        else:
            print("Conformance claims already consistent with ", end="")
        print(f"docs/conformance.json: {summary}.")
        return 0

    problems = check(root, expected)
    if problems:
        print(
            "Stale conformance counts. docs/conformance.json is the authority; "
            "regenerate it and rewrite the prose with `make conformance` "
            "(which runs this script with --write), or fix the wording so the "
            "claim is matched:\n",
            file=sys.stderr,
        )
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1

    print(f"Conformance claims consistent: {summary}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
