#  Copyright (c) 2026. Jose M. Requena-Plens
"""room domain of phonometry (see module docstrings)."""

from __future__ import annotations

from .._plot.geometry import (
    plot_open_plan_geometry,
)
from .crowd_noise import (
    COMMUNICATION_SNR,
    NORMAL_VOICE_POWER_LEVEL,
    PRIVACY_SNR,
    TALKER_DIRECTIVITY,
    CrowdNoiseResult,
    absorption_per_table,
    crowd_noise,
    crowd_noise_level,
    speech_direct_level,
    speech_to_noise_ratio,
)
from .enclosed_space_absorption import (
    ReverberationResult,
    air_absorption_area,
    enclosed_space_reverberation,
    equivalent_absorption_area,
    hard_object_absorption,
    object_fraction,
    reverberation_time,
)
from .image_source import (
    ImageSourceResult,
    audible_image_count,
    image_source_rir,
    reflection_density,
)
from .open_plan import OpenPlanResult, open_plan_metrics
from .reverberation_prediction import (
    ReverberationModelResult,
    arau_puchades_reverberation_time,
    eyring_reverberation_time,
    fitzroy_reverberation_time,
    mean_absorption,
    millington_sette_reverberation_time,
    reverberation_time_models,
    sabine_reverberation_time,
)
from .room_acoustics import (
    DecayCurve,
    RoomAcousticsResult,
    decay_curve,
    room_parameters,
)
from .room_ir import (
    ImpulseResponseResult,
    ImpulseResponseWarning,
    ShapedSweepResult,
    golay_impulse_response,
    golay_pair,
    impulse_response,
    inverse_filter,
    mls_impulse_response,
    mls_signal,
    shaped_sweep_signal,
    sweep_signal,
)
from .room_modes import (
    MODE_KINDS,
    RoomModesResult,
    room_modal_density,
    room_mode_count,
    room_mode_frequency,
    room_modes,
)
from .room_noise import (
    NCResult,
    RCResult,
    nc_curve,
    noise_criterion,
    rc_curve,
    room_criterion,
)
from .steady_field import (
    SOURCE_POWER_MODELS,
    SteadyFieldResult,
    critical_distance,
    room_constant,
    schroeder_frequency,
    steady_state_field,
    steady_state_spl,
)

__all__ = [
    "COMMUNICATION_SNR",
    "MODE_KINDS",
    "NORMAL_VOICE_POWER_LEVEL",
    "PRIVACY_SNR",
    "SOURCE_POWER_MODELS",
    "TALKER_DIRECTIVITY",
    "CrowdNoiseResult",
    "DecayCurve",
    "ImageSourceResult",
    "ImpulseResponseResult",
    "ImpulseResponseWarning",
    "NCResult",
    "OpenPlanResult",
    "RCResult",
    "ReverberationModelResult",
    "ReverberationResult",
    "RoomAcousticsResult",
    "RoomModesResult",
    "ShapedSweepResult",
    "SteadyFieldResult",
    "absorption_per_table",
    "air_absorption_area",
    "arau_puchades_reverberation_time",
    "audible_image_count",
    "critical_distance",
    "crowd_noise",
    "crowd_noise_level",
    "decay_curve",
    "enclosed_space_reverberation",
    "equivalent_absorption_area",
    "eyring_reverberation_time",
    "fitzroy_reverberation_time",
    "golay_impulse_response",
    "golay_pair",
    "hard_object_absorption",
    "image_source_rir",
    "impulse_response",
    "inverse_filter",
    "mean_absorption",
    "millington_sette_reverberation_time",
    "mls_impulse_response",
    "mls_signal",
    "nc_curve",
    "noise_criterion",
    "object_fraction",
    "open_plan_metrics",
    "plot_open_plan_geometry",
    "rc_curve",
    "reflection_density",
    "reverberation_time",
    "reverberation_time_models",
    "room_constant",
    "room_criterion",
    "room_modal_density",
    "room_mode_count",
    "room_mode_frequency",
    "room_modes",
    "room_parameters",
    "sabine_reverberation_time",
    "schroeder_frequency",
    "shaped_sweep_signal",
    "speech_direct_level",
    "speech_to_noise_ratio",
    "steady_state_field",
    "steady_state_spl",
    "sweep_signal",
]
