#  Copyright (c) 2026. Jose M. Requena-Plens
"""Crowd self-noise in a restaurant: the cocktail-party equilibrium.

In a room where the only source of noise is the occupants themselves, the
background against which each conversation has to be understood is generated by
the *other* conversations. Long (*Architectural Acoustics* 2nd ed., Chapter 17,
Equations (17.50) to (17.54)) writes the two competing levels at a listener:

* the **signal**, the direct field of the person across the table
  (Equation (17.50)),

      Lp(signal) = Lw + 10 log10[ Q / (4 pi r^2) ]

* the **noise**, the reverberant field built up by ``N`` simultaneous talkers
  spread over the room (Equation (17.51)),

      Lp(noise) = Lw + 10 log10 N + 10 log10[ 4 / (N A_tab) ]

where ``Lw`` is the sound power level of one talker (about 70 dB for normal
conversation), ``Q`` the talker's directivity factor (about 2 in the forward
direction), ``r`` the talker-to-listener distance and ``A_tab`` the equivalent
absorption area *per occupied table*, so that ``N A_tab`` is the room's total
absorption. Their difference is the speech-to-noise ratio (Equation (17.52)):

    L_SN = 10 log10[ Q / (4 pi r^2) ] + 10 log10[ A_tab / 4 ]

which is independent of the talker's power and of the number of talkers: adding
a table adds both a talker and its share of absorption. What decides whether a
restaurant works is therefore the *absorption per table*, not its total
absorption. Requiring ``L_SN > -6 dB`` for adequate cross-table communication
at a separation ``rs``, and ``L_SN < -9 dB`` for privacy between tables a
distance ``rt`` apart, turns into a pair of design bounds
(Equations (17.53) and (17.54)):

    A_tab > 16 pi 10^(-0.6) rs^2 / Q  ~  6.31 rs^2   (Q = 2)
    A_tab < 16 pi 10^(-0.9) rt^2 / Q  ~  3.16 rt^2   (Q = 2)

.. note::
   Long prints the first constant as ``6.33``; the closed form with the same
   ``Q = 2`` and ``-6 dB`` that yield his second constant ``3.16`` gives
   ``6.31``, which is also what his own conversion of the result ("6.3 or more
   square metres (68 sq ft)") implies (see ``docs/ERRATA.md``). This module
   computes both constants from :func:`speech_to_noise_ratio`, so they stay
   mutually consistent.

   His prose also puts the direct field at an adjacent table 3 m away at
   "about 54 dB", where :func:`speech_direct_level` with the same ``Q = 2``
   and ``L_w = 70 dB`` gives 52.5 dB. That one is left as printed rather than
   reconciled, because the intended reading cannot be established from the
   book; it is recorded under the non-errata notes of ``docs/ERRATA.md``.

The **Lombard reflex** (talkers raising their voices as the background grows)
is deliberately *not* modelled: it cancels out of ``L_SN`` as long as everyone
raises their voice equally, and Long uses the model in exactly that way, as the
explanation of why the level spirals upward in a hard room rather than as a
predictor of the final level.

This is a *design* model for the self-generated noise of an occupied room. The
measurement standard for the spatial decay of speech in an open-plan office is
ISO 3382-3, implemented separately in :mod:`phonometry.room.open_plan`: that
one derives ``D2,S``, the distraction distance and the privacy distance from
measured levels along a line of workstations, and predicts nothing.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

import numpy as np
from numpy.typing import ArrayLike, NDArray

from .._internal.types import as_float_or_array
from .._internal.validation import require_positive

if TYPE_CHECKING:
    from matplotlib.axes import Axes

#: Sound power level of one talker in normal conversation, dB re 1 pW
#: (Long, Chapter 17, "a normal conversational level").
NORMAL_VOICE_POWER_LEVEL = 70.0

#: Directivity factor of a talker in the forward direction (Long Chapter 17).
TALKER_DIRECTIVITY = 2.0

#: Speech-to-noise ratio required for adequate cross-table communication, dB
#: (Long Equation (17.53)).
COMMUNICATION_SNR = -6.0

#: Speech-to-noise ratio below which a neighbouring table is not understood, dB
#: (Long Equation (17.54)).
PRIVACY_SNR = -9.0


def _require_distance(value: ArrayLike, name: str) -> NDArray[np.float64]:
    """Validate a positive, finite distance (scalar or array)."""
    r = np.asarray(value, dtype=np.float64)
    if not np.all(np.isfinite(r)) or np.any(r <= 0.0):
        raise ValueError(f"'{name}' must be positive and finite.")
    return r


def speech_direct_level(
    distance: ArrayLike,
    *,
    sound_power_level: float = NORMAL_VOICE_POWER_LEVEL,
    directivity: float = TALKER_DIRECTIVITY,
) -> np.ndarray | float:
    """Direct-field level of one talker (Long Equation (17.50)).

    ``Lp = Lw + 10 log10[Q / (4 pi r^2)]``, the signal a listener across the
    table receives.

    :param distance: Talker-to-listener distance ``r``, m (scalar or array).
    :param sound_power_level: Talker sound power level ``Lw``, dB re 1 pW
        (default :data:`NORMAL_VOICE_POWER_LEVEL`).
    :param directivity: Talker directivity factor ``Q`` (default
        :data:`TALKER_DIRECTIVITY`).
    :return: The direct-field sound pressure level, dB.
    """
    r = _require_distance(distance, "distance")
    q = require_positive(directivity, "directivity")
    lw = float(sound_power_level)
    return as_float_or_array(lw + 10.0 * np.log10(q / (4.0 * np.pi * r**2)))


def crowd_noise_level(
    talkers: ArrayLike,
    absorption_area: ArrayLike,
    *,
    sound_power_level: float = NORMAL_VOICE_POWER_LEVEL,
) -> np.ndarray | float:
    """Reverberant level of ``N`` simultaneous talkers (Long Equation (17.51)).

    ``Lp = Lw + 10 log10 N + 10 log10(4 / A)`` with the room's total
    equivalent absorption area ``A`` (``= N A_tab`` when the absorption is
    counted per occupied table).

    :param talkers: Number ``N`` of simultaneous talkers (scalar or array,
        at least 1).
    :param absorption_area: Total equivalent absorption area ``A`` of the
        room, metric sabins (m2) (scalar or array).
    :param sound_power_level: Sound power level ``Lw`` of one talker,
        dB re 1 pW (default :data:`NORMAL_VOICE_POWER_LEVEL`).
    :return: The self-generated reverberant level, dB.
    """
    n = np.asarray(talkers, dtype=np.float64)
    if not np.all(np.isfinite(n)) or np.any(n < 1.0):
        raise ValueError("'talkers' must be at least 1 and finite.")
    a = np.asarray(absorption_area, dtype=np.float64)
    if not np.all(np.isfinite(a)) or np.any(a <= 0.0):
        raise ValueError("'absorption_area' must be positive and finite.")
    lw = float(sound_power_level)
    return as_float_or_array(lw + 10.0 * np.log10(n) + 10.0 * np.log10(4.0 / a))


def speech_to_noise_ratio(
    distance: ArrayLike,
    absorption_per_table: ArrayLike,
    *,
    directivity: float = TALKER_DIRECTIVITY,
) -> np.ndarray | float:
    """Speech-to-noise ratio across a table (Long Equation (17.52)).

    ``L_SN = 10 log10[Q / (4 pi r^2)] + 10 log10[A_tab / 4]``, the difference
    between Equations (17.50) and (17.51). Neither the talker's power nor the
    number of talkers appears: a busier room brings its own absorption with it.

    :param distance: Talker-to-listener distance ``r``, m.
    :param absorption_per_table: Equivalent absorption area per occupied table
        ``A_tab``, m2.
    :param directivity: Talker directivity factor ``Q``.
    :return: The speech-to-noise ratio, dB.
    """
    r = _require_distance(distance, "distance")
    a_tab = np.asarray(absorption_per_table, dtype=np.float64)
    if not np.all(np.isfinite(a_tab)) or np.any(a_tab <= 0.0):
        raise ValueError("'absorption_per_table' must be positive and finite.")
    q = require_positive(directivity, "directivity")
    return as_float_or_array(
        10.0 * np.log10(q / (4.0 * np.pi * r**2)) + 10.0 * np.log10(a_tab / 4.0)
    )


def absorption_per_table(
    distance: ArrayLike,
    speech_to_noise: float,
    *,
    directivity: float = TALKER_DIRECTIVITY,
) -> np.ndarray | float:
    """Absorption per table giving a chosen ``L_SN`` (inverse of (17.52)).

    ``A_tab = 16 pi r^2 10^(L_SN/10) / Q``. With ``L_SN = -6 dB`` this is
    Long's communication bound (Equation (17.53)), with ``-9 dB`` his privacy
    bound (Equation (17.54)).

    :param distance: Separation ``r``, m: the cross-table distance ``rs`` for
        the communication bound, the table-to-table distance ``rt`` for the
        privacy bound.
    :param speech_to_noise: Target speech-to-noise ratio ``L_SN``, dB.
    :param directivity: Talker directivity factor ``Q``.
    :return: The equivalent absorption area per table ``A_tab``, m2.
    """
    r = _require_distance(distance, "distance")
    q = require_positive(directivity, "directivity")
    snr = float(speech_to_noise)
    if not np.isfinite(snr):
        raise ValueError("'speech_to_noise' must be finite.")
    return as_float_or_array(16.0 * np.pi * r**2 * 10.0 ** (snr / 10.0) / q)


@dataclass(frozen=True)
class CrowdNoiseResult:
    """Self-generated noise of an occupied room versus occupancy and absorption.

    :ivar talkers: Number of simultaneous talkers on the occupancy axis.
    :ivar absorption_areas: Total room absorption areas compared, m2, one per
        row of :attr:`levels`.
    :ivar levels: Reverberant self-noise level, dB, shaped
        ``(len(absorption_areas), len(talkers))``.
    :ivar signal_level: Direct-field level of the talker across the table, dB.
    :ivar distance: Talker-to-listener distance ``r``, m.
    :ivar sound_power_level: Sound power level of one talker, dB re 1 pW.
    :ivar directivity: Talker directivity factor ``Q``.
    :ivar communication_level: Noise level at which the speech-to-noise ratio
        falls to :data:`COMMUNICATION_SNR`, dB: above it, cross-table
        conversation stops working.
    """

    talkers: np.ndarray
    absorption_areas: np.ndarray
    levels: np.ndarray
    signal_level: float
    distance: float
    sound_power_level: float
    directivity: float
    communication_level: float

    def speech_to_noise(self) -> np.ndarray:
        """Speech-to-noise ratio for every point of :attr:`levels`, dB."""
        return self.signal_level - self.levels

    def plot(
        self, ax: Axes | None = None, *, language: str = "en", **kwargs: Any
    ) -> Axes:
        """Plot the self-noise level against occupancy, one curve per absorption.

        The direct-field level of the talker across the table and the
        speech-to-noise limit of Equation (17.53) are drawn as references, so
        the crossing point reads directly as the occupancy at which the room
        stops working. Requires matplotlib
        (``pip install phonometry[plot]``).
        """
        from .._i18n import check_language
        from .._plot.room import plot_crowd_noise

        check_language(language)
        return plot_crowd_noise(self, ax=ax, language=language, **kwargs)


def crowd_noise(
    absorption_areas: ArrayLike,
    *,
    talkers: ArrayLike | None = None,
    distance: float = 1.2,
    sound_power_level: float = NORMAL_VOICE_POWER_LEVEL,
    directivity: float = TALKER_DIRECTIVITY,
) -> CrowdNoiseResult:
    """Self-noise of an occupied room versus occupancy (Long 17.50-17.52).

    Evaluates Equation (17.51) over an occupancy axis for each of the supplied
    total absorption areas, together with the direct-field signal of
    Equation (17.50) at the listener across the table.

    :param absorption_areas: Total equivalent absorption areas ``A`` of the
        room to compare, m2 (scalar or 1-D).
    :param talkers: Occupancy axis ``N``, the number of simultaneous talkers;
        default the integers ``1..20``.
    :param distance: Talker-to-listener distance ``r``, m (default 1.2 m,
        Long's cross-table distance).
    :param sound_power_level: Sound power level ``Lw`` of one talker, dB re
        1 pW (default :data:`NORMAL_VOICE_POWER_LEVEL`).
    :param directivity: Talker directivity factor ``Q`` (default
        :data:`TALKER_DIRECTIVITY`).
    :return: A :class:`CrowdNoiseResult`.
    """
    areas = np.atleast_1d(np.asarray(absorption_areas, dtype=np.float64))
    if areas.ndim != 1 or areas.size == 0:
        raise ValueError("'absorption_areas' must be a non-empty 1-D array.")
    if not np.all(np.isfinite(areas)) or np.any(areas <= 0.0):
        raise ValueError("'absorption_areas' must be positive and finite.")
    n = (
        np.arange(1.0, 21.0)
        if talkers is None
        else np.atleast_1d(np.asarray(talkers, dtype=np.float64))
    )
    if n.ndim != 1 or n.size == 0:
        raise ValueError("'talkers' must be a non-empty 1-D array.")
    if not np.all(np.isfinite(n)) or np.any(n < 1.0):
        raise ValueError("'talkers' must be at least 1 and finite.")

    r = require_positive(distance, "distance")
    q = require_positive(directivity, "directivity")
    lw = float(sound_power_level)

    levels = np.asarray(
        crowd_noise_level(n[None, :], areas[:, None], sound_power_level=lw),
        dtype=np.float64,
    )
    signal = float(
        np.asarray(
            speech_direct_level(r, sound_power_level=lw, directivity=q)
        )[()]
    )
    return CrowdNoiseResult(
        talkers=n,
        absorption_areas=areas,
        levels=levels,
        signal_level=signal,
        distance=float(r),
        sound_power_level=lw,
        directivity=float(q),
        communication_level=signal - COMMUNICATION_SNR,
    )
