#  Copyright (c) 2026. Jose Manuel Requena Plens
"""Acoustic materials: absorption, airflow resistance, scattering, diffusion.

What a surface does to sound that arrives at it. The absorption side runs
from the impedance tube (ISO 10534-1) and the airflow resistance
(ISO 9053-2) through the empirical porous models (Delany-Bazley, Miki) and
the microperforated panel of Maa to the single-number rating of ISO 11654
and its uncertainty in ISO 12999-2; the in-situ method of ISO 13472 sits
beside them because it measures the same quantity on a road surface.

The scattering side is the same surface answered differently: the random
incidence scattering coefficient of ISO 17497-1, the directional diffusion
coefficient of ISO 17497-2 and the quadratic-residue diffuser that Cox and
D'Antonio work through in Appendix B of the third edition.
"""

from __future__ import annotations

# ---------------------------------------------------------------------------
# ISO 11654:1997 rating of sound absorption — the two normative worked examples
# of Annex A. Both use the same practical-coefficient spectrum except at 500 Hz;
# A.1 gives alpha_w = 0,60 with no shape indicator, A.2 (500 Hz raised to 1,00)
# gives alpha_w = 0,60(M). Bands are 250/500/1000/2000/4000 Hz. Mirrors
# tests/materials/absorbers/test_absorption_rating.py.
# ---------------------------------------------------------------------------
ISO11654_ANNEX_A1_ALPHA_P: tuple[float, ...] = (0.35, 0.70, 0.65, 0.60, 0.55)
ISO11654_ANNEX_A1_ALPHA_W = 0.60
ISO11654_ANNEX_A1_CLASS = "C"
ISO11654_ANNEX_A1_INDICATOR = ""
ISO11654_ANNEX_A2_ALPHA_P: tuple[float, ...] = (0.35, 1.00, 0.65, 0.60, 0.55)
ISO11654_ANNEX_A2_ALPHA_W = 0.60
ISO11654_ANNEX_A2_INDICATOR = "M"

# ---------------------------------------------------------------------------
# ISO 9053-2:2020 alternating-method airflow resistance — the Annex A.3 worked
# example of the effective ratio of specific heats. A closed cylinder 100 mm x
# 100 mm gives V = 7,854e-4 m3 and S = 0,0471 m2; with the IEC 61094-2:2009 air
# properties at 23 C and f = 2 Hz the standard prints b = 1,83e-3 m and the
# heat-conduction-corrected kappa' = kappa*0,978 = 1,370. Mirrors
# tests/materials/absorbers/test_airflow_resistance.py.
# ---------------------------------------------------------------------------
ISO9053_2_ANNEX_A_SURFACE = 0.0471  # S (m2)
ISO9053_2_ANNEX_A_VOLUME = 7.854e-4  # V (m3)
ISO9053_2_ANNEX_A_FREQUENCY = 2.0  # f (Hz)
ISO9053_2_ANNEX_A_BOUNDARY_LAYER = 1.83e-3  # b (m)
ISO9053_2_ANNEX_A_KAPPA_PRIME = 1.370  # kappa' = kappa*0,978

# ---------------------------------------------------------------------------
# ISO 10534-1:1996 standing-wave-ratio method — closed-form physics oracle from
# Eqs (13)/(14)/(9): a standing-wave ratio s = 3 gives |r| = (s-1)/(s+1) = 0,5
# and absorption alpha = 1 - |r|^2 = 0,75.
# ---------------------------------------------------------------------------
ISO10534_1_SWR = 3.0
ISO10534_1_REFLECTION_MAGNITUDE = 0.5
ISO10534_1_ABSORPTION = 0.75

# ---------------------------------------------------------------------------
# ISO 17497-1:2004 random-incidence scattering coefficient. Eq (2) fixes the
# reference speed of sound c = 343,2 m/s at 20 C. The synthetic worked chain
# (T1..T4 = 8,0/6,0/7,5/5,0 s, V/S from V = 200 m3, S = 10 m2) exercises the
# Sabine absorptions Eq (1)/(4) and the scattering Eq (5). Mirrors
# tests/materials/diffusers/test_scattering_diffusion.py.
# ---------------------------------------------------------------------------
ISO17497_1_SPEED_OF_SOUND_20C = 343.2  # Eq (2) reference condition (m/s)
ISO17497_1_CHAIN_V = 200.0  # chamber volume V (m3)
ISO17497_1_CHAIN_S = 10.0  # sample area S (m2)
ISO17497_1_CHAIN_C = 343.2  # speed of sound used throughout (m/s)
ISO17497_1_CHAIN_T: tuple[float, float, float, float] = (8.0, 6.0, 7.5, 5.0)
ISO17497_1_CHAIN_ALPHA_S = 0.1342754467754468  # random-incidence absorption
ISO17497_1_CHAIN_ALPHA_SPEC = 0.21484071484071485  # specular absorption
ISO17497_1_CHAIN_SCATTERING = 0.09306108711505018  # s = (a_spec-a_s)/(1-a_s)
# Annex A.5 combined uncertainty of the scattering coefficient. For
# a_spec = 0,6, a_s = 0,3 with u(a_spec) = 0,02 and u(a_s) = 0,01 the
# error-propagation form gives u(s) = 0,0297.
ISO17497_1_A5_ALPHA_SPEC = 0.6
ISO17497_1_A5_ALPHA_S = 0.3
ISO17497_1_A5_U_ALPHA_SPEC = 0.02
ISO17497_1_A5_U_ALPHA_S = 0.01
ISO17497_1_A5_U_SCATTERING = 0.0297147342419613  # combined u(s)

# ---------------------------------------------------------------------------
# ISO 17497-2:2012 directional diffusion coefficient d_theta, Formula (5).
# Arithmetic oracle on the standard single-plane semicircular receiver arc
# (37 receivers at 5 deg spacing, -90..+90 deg): the committed levels are
# GENERATED BY THIS LIBRARY'S OWN Fraunhofer far-field phase-grating model
# (materials/diffusers/design.py, Cox & D'Antonio Eq. (5.8)/(9.32)) for a
# published diffuser geometry; they are model output, not third-party data.
# The independent external anchor against published third-party BEM values is
# the Cox & D'Antonio Appendix B comparison further below.
#
# Geometry (published): an N = 7 quadratic-residue diffuser, 6 periods,
# 3.6 m total width, 0.2 m maximum well depth - the "N = 7 QRD, 6 periods,
# 0.2 m deep" row of Cox & D'Antonio, "Acoustic Absorbers and Diffusers",
# 3rd ed. (2017), Appendix B section 7 (Schroeder diffusers, 3.6 m wide).
# The commercial single-plane QRD measured by Hargreaves, Cox, Lam & D'Antonio,
# J. Acoust. Soc. Am. 108(4), 1710-1720 (2000), Table I is the same diffuser
# family (N = 7, 0.2 m maximum well depth). Period 3.6/6 = 0.6 m, well width
# 3.6/42 m; well depths d_n = s_n lambda0 / (2 N) (Eq. (10.3), s_n = n^2 mod 7)
# with design frequency f0 = 490 Hz (c = 343 m/s), so the deepest well
# (s_max = 4) is exactly 0.2 m: depths = (0, 0.05, 0.2, 0.1, 0.1, 0.2, 0.05) m.
# Prediction at 1000 Hz, normal incidence. The flat reference is the model's
# own normalisation pathway: the same 3.6 m footprint with all wells at zero
# depth (Hargreaves et al. used a 0.57 m plane panel; the Fraunhofer model
# normalises against the equal-footprint flat panel instead, as
# predicted_diffusion_spectrum does).
#
# Levels are peak-referenced (0 dB at the maximum; Formula (5) is invariant
# to a constant level shift), rounded to 1e-3 dB; the coefficients below are
# recomputed from the rounded committed levels, so the conformance/test
# tolerance is a tight 1e-6 (exact arithmetic on the committed levels). Six
# periods of a periodic QRD concentrate the reflected energy into grating
# lobes, so d_theta is modest - consistent with the low published Appendix B
# values for periodic arrays (Cox & D'Antonio section 5.2.5).
ISO17497_2_QRD_N = 7  # quadratic-residue prime N
ISO17497_2_QRD_PERIODS = 6  # periods across the 3.6 m array
ISO17497_2_QRD_TOTAL_WIDTH = 3.6  # m, published total array width
ISO17497_2_QRD_WELL_WIDTH = 3.6 / 42  # m, period 0.6 m / N = 7 wells
ISO17497_2_QRD_MAX_DEPTH = 0.2  # m, published maximum well depth
ISO17497_2_QRD_DESIGN_FREQUENCY = 490.0  # Hz, gives the 0.2 m deepest well
ISO17497_2_SPEED_OF_SOUND = 343.0  # m/s, used throughout the prediction
ISO17497_2_PREDICTION_FREQUENCY = 1000.0  # Hz, single-frequency arc below
ISO17497_2_QRD_LEVELS: tuple[float, ...] = (
    -19.337, -18.867, -19.798, -26.178, -26.347, -18.811, -29.685, -18.212,
    -34.309, -13.850, -11.212, -1.191, -12.143, -16.334, -21.342, -25.559,
    -24.896, -22.567, 0.000, -19.414, -18.483, -17.966, -17.789, -16.949,
    -13.506, -1.146, -9.559, -10.912, -30.481, -13.875, -25.163, -14.346,
    -22.085, -22.176, -16.038, -15.275, -15.804,
)
ISO17497_2_FLAT_LEVELS: tuple[float, ...] = (
    -36.385, -35.709, -36.065, -41.617, -40.861, -32.474, -42.750, -31.127,
    -47.771, -28.995, -30.520, -50.381, -28.015, -23.478, -21.660, -20.958,
    -20.753, -20.733, 0.000, -20.733, -20.753, -20.958, -21.660, -23.478,
    -28.015, -50.381, -30.520, -28.995, -47.771, -31.127, -42.750, -32.474,
    -40.861, -41.617, -36.065, -35.709, -36.385,
)
ISO17497_2_QRD_DIFFUSION = 0.10985146785866741  # d_theta of the QRD arc, Formula (5)
ISO17497_2_FLAT_DIFFUSION = 0.004871959138901796  # d_theta of the flat reference arc
ISO17497_2_NORMALIZED_DIFFUSION = 0.10549346858814809  # d_theta_n, Formula (7)
# ---------------------------------------------------------------------------
# External anchor: Cox & D'Antonio, "Acoustic Absorbers and Diffusers",
# 3rd ed. (2017), Appendix B "Normalized diffusion coefficient table"
# (pp. 481-485), section 7, row "N = 7 QRD, 6 periods, 0.2 m deep", normal
# incidence. Third-party published data: 2D BEM predictions (thin-panel
# extrusions, source at 100 m, receiver arc at 50 m; each one-third-octave
# polar response is the average of seven single-frequency responses -
# section 5.2.5). Our Fraunhofer model reproduces the published normalised
# diffusion coefficient d_n in the 200-400 Hz one-third-octave bands within
# 0.01 (asserted at +/-0.015). CAVEAT: this is a low-band anchor, not
# full-band conformance - across the full published 100-5000 Hz range at
# normal incidence the model-vs-BEM mean absolute deviation is ~0.09 (the
# far-field phase-grating model ignores the edge diffraction and near-grazing
# effects the BEM resolves).
# ---------------------------------------------------------------------------
COX3E_APPENDIX_B_QRD_BANDS: tuple[float, ...] = (200.0, 250.0, 315.0, 400.0)
COX3E_APPENDIX_B_QRD_DN: tuple[float, ...] = (0.00, 0.01, 0.01, 0.01)
COX3E_APPENDIX_B_TOLERANCE = 0.015  # |model d_n - published BEM d_n| bound
# Formula (8) area factors use RADIANS internally, so the zenith weight is
# N0 = (4*pi/dphi)*sin^2(dtheta/4) / A_min with dtheta = dphi = 5 deg.
ISO17497_2_AREA_FACTOR_ZENITH = 1.571045588794762  # N0, radians convention

# ---------------------------------------------------------------------------
# Diffuser-design far-field prediction (Cox & D'Antonio, Fraunhofer model).
# Analytic anchors for the QRD-vs-flat behaviour of the design predictor.
#
# Geometry: an N = 7 quadratic residue diffuser (Eq. (10.2), s_n = n^2 mod N,
# so s = {0,1,4,2,2,4,1}) with design frequency f0 = 500 Hz and c = 343 m/s
# has design wavelength lambda0 = 0,686 m. The deepest well (s_max = 4) has,
# by Eq. (10.3) d_n = s_n*lambda0/(2N), depth 4*0,686/14 = 0,196 m exactly.
DIFFUSER_QRD7_MAX_DEPTH = 0.196  # m, closed form d_max = s_max*c/(2 N f0)
# A flat panel (all wells zero depth) normalises against itself, so Formula (7)
# gives (d - d_ref)/(1 - d_ref) = 0 identically: the exact zero anchor.
DIFFUSER_FLAT_NORMALIZED_DIFFUSION = 0.0
# The same N = 7 QRD (10 cm wells, five periods) predicted at 2 kHz: the
# normalised diffusion is well above the flat-panel zero, as a diffuser must be.
# The value is the far-field model prediction, committed as a regression guard.
DIFFUSER_QRD7_NORMALIZED_DIFFUSION_2K = 0.20802829817091092

# ---------------------------------------------------------------------------
# ISO 13472-1:2002 in-situ road-surface absorption. The mandatory geometry
# ds = 1,25 m, dm = 0,25 m gives the geometrical-spreading factor Kr = 2/3
# (Clause 4.2). The Annex A worked example (c = 340 m/s, 5 ms flat window)
# gives a maximum-sampled-area radius r ~ 1,34 m. Mirrors
# tests/materials/surfaces/test_road_absorption.py.
# ---------------------------------------------------------------------------
ISO13472_1_KR = 2.0 / 3.0  # geometrical-spreading factor
ISO13472_1_MSA_WINDOW = 5.0e-3  # reflected-wave window width Tw (s)
ISO13472_1_MSA_RADIUS = 1.3425466996067585  # Annex A worked example (m)

# ---------------------------------------------------------------------------
# ISO 13472-2:2010 spot method. The upper usable (plane-wave) frequency of a
# circular tube is f_u = 0,58 c0/d (Clause 5.4.1); a 100 mm tube at
# c0 = 343 m/s gives f_u = 1989,4 Hz.
# ---------------------------------------------------------------------------
ISO13472_2_SPOT_DIAMETER = 0.100  # tube diameter d (m)
ISO13472_2_SPOT_SPEED = 343.0  # speed of sound c0 (m/s)
ISO13472_2_SPOT_FU = 1989.4  # upper usable frequency (Hz)

# ---------------------------------------------------------------------------
# ISO 12999-2:2020 - measurement uncertainty for sound absorption.
# The standard's own worked examples are the oracle: Table 4 (sound absorption
# coefficient alpha_s and expanded uncertainty +/-U at k=2, reproducibility,
# one-third-octave 63-5000 Hz) and Table 5 (practical coefficient alpha_p,
# octave 250-4000 Hz). Example 1: alpha_w = 0,70 (MH) +/- 0,07 (k=2);
# Example 2: DLalpha,NRD = (8,1 +/- 1,6) dB (k=2).
# ---------------------------------------------------------------------------
ISO12999_2_TABLE4_FREQ = [
    63, 80, 100, 125, 160, 200, 250, 315, 400, 500,
    630, 800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000,
]
ISO12999_2_TABLE4_ALPHA_S = [
    0.33, 0.35, 0.39, 0.38, 0.37, 0.36, 0.36, 0.36, 0.43, 0.49,
    0.58, 0.63, 0.68, 0.71, 0.73, 0.75, 0.77, 0.79, 0.81, 0.81,
]
ISO12999_2_TABLE4_U_K2 = [
    0.33, 0.26, 0.22, 0.17, 0.13, 0.11, 0.09, 0.08, 0.08, 0.08,
    0.08, 0.08, 0.08, 0.09, 0.09, 0.09, 0.10, 0.11, 0.13, 0.16,
]
ISO12999_2_TABLE5_FREQ = [250, 500, 1000, 2000, 4000]
ISO12999_2_TABLE5_ALPHA_P = [0.50, 0.65, 0.70, 0.85, 0.80]
ISO12999_2_TABLE5_U_K2 = [0.09, 0.08, 0.08, 0.08, 0.10]
ISO12999_2_ALPHA_W_EXAMPLE = 0.70
ISO12999_2_ALPHA_W_U_K2 = 0.07
ISO12999_2_DLALPHA_EXAMPLE = 8.1
ISO12999_2_DLALPHA_U_K2 = 1.6

# Porous materials & multilayer absorbers - published anchors.
#
# Delany-Bazley power law (Bies 5e Appendix D Table D.1 first row = Mechel 2e
# Sect. G.11 Eqs. (1)-(2) = Hopkins Eqs. (1.171)-(1.172)), evaluated by hand
# at the digitization point X = rho f / sigma = 0.1 (mid fit range):
#   Zc/(rho c) = 1 + 0.0571*0.1^-0.754 - j 0.087*0.1^-0.732
#   k/k0       = 1 + 0.0978*0.1^-0.700 - j 0.189*0.1^-0.595
# Miki (1990) Eqs. (30)-(34) evaluated by hand at f/sigma = 0.1:
#   Zc/(rho c) = 1 + 0.070*0.1^-0.632 - j 0.107*0.1^-0.632
#   k/k0       = 1 + 0.109*0.1^-0.618 - j 0.160*0.1^-0.618
# Mechel 2e Sect. D.5: the maximum possible statistical absorption
# coefficient of a locally reacting plane is the published 0.951.
# ---------------------------------------------------------------------------
POROUS_DB_X_POINT = 0.1
POROUS_DB_ZC_EXPECTED = 1.3240679696882804 - 0.46937424158816093j
POROUS_DB_K_EXPECTED = 1.4901611144874722 - 0.7438096426114194j
POROUS_MIKI_Y_POINT = 0.1
POROUS_MIKI_ZC_EXPECTED = 1.2999839642782076 - 0.4585469168252603j
POROUS_MIKI_K_EXPECTED = 1.4522999064714557 - 0.6639264682149806j
POROUS_STATISTICAL_ALPHA_MAX = 0.951

# ---------------------------------------------------------------------------
# Maa (1998), "Potential of microperforated panel absorber", JASA 104(5).
# Table I (printed): maximum absorption alpha0 = 4r/(1+r)^2 (Eq. (10)) and
# absorption-band frequency interval B = f2/f1 = pi/arccot(1+r) - 1
# (Eq. (21)) for r = 1..5 at k = 0.
# Fig. 5 design example (also Cox & D'Antonio 3e Fig. 7.28): d = t = 0.2 mm,
# hole separation b = 2.5 mm on a square lattice (sigma = (pi/4)(d/b)^2,
# Eq. (25)), cavity D = 6 cm; theory vs standing-wave-tube measurement.
# ---------------------------------------------------------------------------
MAA_TABLE_I_R = (1.0, 2.0, 3.0, 4.0, 5.0)
MAA_TABLE_I_ALPHA0 = (1.0, 0.89, 0.75, 0.64, 0.56)
MAA_TABLE_I_BANDWIDTH = (5.78, 8.76, 11.82, 14.91, 18.02)
MAA_FIG5_DIAMETER = 0.2e-3
MAA_FIG5_THICKNESS = 0.2e-3
MAA_FIG5_SEPARATION = 2.5e-3
MAA_FIG5_CAVITY = 0.06
