#  Copyright (c) 2026. Jose Manuel Requena Plens
"""materials.diffusers subdomain of phonometry: surfaces that scatter, and the methods that characterise them."""

from __future__ import annotations

from .design import (
    DEFAULT_POLAR_ANGLES,
    DiffuserPolarResponse,
    predict_diffuser_polar_response,
    predicted_diffusion_spectrum,
    qrd_well_depths,
    quadratic_residue_sequence,
)
from .metadiffuser import (
    MetadiffuserResult,
    MetadiffuserWell,
    metadiffuser_diffusion_spectrum,
    metadiffuser_polar_response,
    metadiffuser_reflection,
)
from .reverberation_room_scattering import (
    BASE_PLATE_BANDS,
    BASE_PLATE_MAX_SCATTERING,
    ScatteringDiffusionWarning,
    ScatteringResult,
    ScatteringUncertainty,
    absorption_coefficient_uncertainty,
    air_attenuation_coefficient,
    base_plate_scattering,
    check_base_plate_scattering,
    random_incidence_absorption,
    reverberation_time_uncertainty,
    scattering_coefficient,
    scattering_coefficient_spectrum,
    scattering_coefficient_uncertainty,
    specular_absorption_coefficient,
    speed_of_sound_iso17497,
)
from .scattering_diffusion import (
    TWO_DIMENSIONAL_SOURCE_WEIGHTS,
    DiffusionResult,
    DiffusionSpectrum,
    area_factors,
    diffusion_spectrum,
    directional_diffusion,
    directional_diffusion_coefficient,
    normalized_diffusion_coefficient,
    random_incidence_diffusion,
)

__all__ = [
    "BASE_PLATE_BANDS",
    "BASE_PLATE_MAX_SCATTERING",
    "DEFAULT_POLAR_ANGLES",
    "TWO_DIMENSIONAL_SOURCE_WEIGHTS",
    "DiffuserPolarResponse",
    "DiffusionResult",
    "DiffusionSpectrum",
    "MetadiffuserResult",
    "MetadiffuserWell",
    "ScatteringDiffusionWarning",
    "ScatteringResult",
    "ScatteringUncertainty",
    "absorption_coefficient_uncertainty",
    "air_attenuation_coefficient",
    "area_factors",
    "base_plate_scattering",
    "check_base_plate_scattering",
    "diffusion_spectrum",
    "directional_diffusion",
    "directional_diffusion_coefficient",
    "metadiffuser_diffusion_spectrum",
    "metadiffuser_polar_response",
    "metadiffuser_reflection",
    "normalized_diffusion_coefficient",
    "predict_diffuser_polar_response",
    "predicted_diffusion_spectrum",
    "qrd_well_depths",
    "quadratic_residue_sequence",
    "random_incidence_absorption",
    "random_incidence_diffusion",
    "reverberation_time_uncertainty",
    "scattering_coefficient",
    "scattering_coefficient_spectrum",
    "scattering_coefficient_uncertainty",
    "specular_absorption_coefficient",
    "speed_of_sound_iso17497",
]
