#  Copyright (c) 2026. Jose M. Requena-Plens
"""underwater domain of phonometry (see module docstrings)."""

from __future__ import annotations

from .acoustics import (
    UNDERWATER_REFERENCE_EXPOSURE,
    UNDERWATER_REFERENCE_PRESSURE,
    in_air_to_underwater_spl,
    peak_sound_pressure_level,
    sound_exposure_level,
    sound_pressure_level,
    underwater_to_in_air_spl,
)
from .marine_mammal_audiograms import (
    AUDIOGRAM_GROUPS,
    BEST_HEARING_FREQUENCY_KHZ,
    ORCA_AUDIOGRAM_RANGE_KHZ,
    AudiogramParameters,
    AudiogramResult,
    audiogram_parameters,
    group_audiogram,
    orca_audiogram,
)
from .marine_mammal_weighting import (
    WEIGHTING_GUIDANCE,
    AuditoryWeightingResult,
    ExposureCriteria,
    WeightedExposureResult,
    WeightingParameters,
    auditory_weighting,
    exposure_criteria,
    hearing_groups,
    weighted_exposure,
    weighting_parameters,
)
from .numerical_propagation import (
    NormalModeResult,
    ParabolicEquationResult,
    RayTraceResult,
    normal_modes,
    parabolic_equation,
    ray_trace,
)
from .ocean_ambient_noise import (
    AmbientNoiseResult,
    ocean_ambient_noise,
    thermal_noise_spectrum,
    wind_noise_spectrum,
)
from .pile_driving_noise import (
    PileStrikeResult,
    StrikeSelSpectrum,
    cumulative_sel,
    cumulative_sel_identical,
    pile_strike_metrics,
    single_strike_sel,
    strike_sel_spectrum,
)
from .propagation import (
    TransmissionLossResult,
    seawater_absorption,
    spreading_loss,
    transmission_loss,
)
from .seabed_reflection import (
    BottomLossResult,
    SeabedReflection,
    bottom_reflection_loss,
    critical_angle,
    reflection_coefficient,
    seabed_reflection,
)
from .ship_radiated_noise import (
    ShipSourceLevelResult,
    hydrophone_depths,
    monopole_source_level,
    radiated_noise_level,
    source_level_uncertainty,
)
from .ship_traffic_noise import (
    VESSEL_CLASSES,
    ShipTrafficSpectrum,
    ship_source_spectrum,
)
from .sonar_equation import (
    DetectionRangeResult,
    SonarEquationResult,
    active_sonar_equation,
    detection_range,
    detection_range_from_curve,
    passive_sonar_equation,
)
from .sound_speed import (
    SoundSpeedProfile,
    depth_to_pressure,
    sea_water_sound_speed,
    sound_speed_profile,
)
from .weston_regimes import (
    WESTON_REGIMES,
    WESTON_SEABEDS,
    WestonPropagationResult,
    WestonRegimeBoundaries,
    WestonSeabed,
    critical_grazing_angle,
    effective_depth,
    loss_parameter,
    reflection_loss_gradient,
    waveguide_cutoff_frequency,
    weston_propagation_loss,
    weston_regime_boundaries,
)

__all__ = [
    "AUDIOGRAM_GROUPS",
    "BEST_HEARING_FREQUENCY_KHZ",
    "ORCA_AUDIOGRAM_RANGE_KHZ",
    "UNDERWATER_REFERENCE_EXPOSURE",
    "UNDERWATER_REFERENCE_PRESSURE",
    "VESSEL_CLASSES",
    "WEIGHTING_GUIDANCE",
    "WESTON_REGIMES",
    "WESTON_SEABEDS",
    "AmbientNoiseResult",
    "AudiogramParameters",
    "AudiogramResult",
    "AuditoryWeightingResult",
    "BottomLossResult",
    "DetectionRangeResult",
    "ExposureCriteria",
    "NormalModeResult",
    "ParabolicEquationResult",
    "PileStrikeResult",
    "RayTraceResult",
    "SeabedReflection",
    "ShipSourceLevelResult",
    "ShipTrafficSpectrum",
    "SonarEquationResult",
    "SoundSpeedProfile",
    "StrikeSelSpectrum",
    "TransmissionLossResult",
    "WeightedExposureResult",
    "WeightingParameters",
    "WestonPropagationResult",
    "WestonRegimeBoundaries",
    "WestonSeabed",
    "active_sonar_equation",
    "audiogram_parameters",
    "auditory_weighting",
    "bottom_reflection_loss",
    "critical_angle",
    "critical_grazing_angle",
    "cumulative_sel",
    "cumulative_sel_identical",
    "depth_to_pressure",
    "detection_range",
    "detection_range_from_curve",
    "effective_depth",
    "exposure_criteria",
    "group_audiogram",
    "hearing_groups",
    "hydrophone_depths",
    "in_air_to_underwater_spl",
    "loss_parameter",
    "monopole_source_level",
    "normal_modes",
    "ocean_ambient_noise",
    "orca_audiogram",
    "parabolic_equation",
    "passive_sonar_equation",
    "peak_sound_pressure_level",
    "pile_strike_metrics",
    "radiated_noise_level",
    "ray_trace",
    "reflection_coefficient",
    "reflection_loss_gradient",
    "sea_water_sound_speed",
    "seabed_reflection",
    "seawater_absorption",
    "ship_source_spectrum",
    "single_strike_sel",
    "sound_exposure_level",
    "sound_pressure_level",
    "sound_speed_profile",
    "source_level_uncertainty",
    "spreading_loss",
    "strike_sel_spectrum",
    "thermal_noise_spectrum",
    "transmission_loss",
    "underwater_to_in_air_spl",
    "waveguide_cutoff_frequency",
    "weighted_exposure",
    "weighting_parameters",
    "weston_propagation_loss",
    "weston_regime_boundaries",
    "wind_noise_spectrum",
]
