#  Copyright (c) 2026. Jose Manuel Requena Plens
"""underwater domain of phonometry (see module docstrings).

Three families since 4.0, along the three questions an underwater problem
asks: :mod:`~phonometry.underwater.sources` for what makes the sound,
:mod:`~phonometry.underwater.propagation` for how it gets there, and
:mod:`~phonometry.underwater.bioacoustics` for who hears it. The ISO 18405
quantities and the sonar equation stay at the root, because all three
families are written in their terms. Every public name is still exported
here, so ``from phonometry import underwater`` reads as it did.
"""

from __future__ import annotations

from .._compat import _namespace_dir, _namespace_shim
from .acoustics import (
    UNDERWATER_REFERENCE_EXPOSURE,
    UNDERWATER_REFERENCE_PRESSURE,
    in_air_to_underwater_spl,
    peak_sound_pressure_level,
    sound_exposure_level,
    sound_pressure_level,
    underwater_to_in_air_spl,
)
from .bioacoustics import (
    AUDIOGRAM_GROUPS,
    BEST_HEARING_FREQUENCY_KHZ,
    ORCA_AUDIOGRAM_RANGE_KHZ,
    WEIGHTING_GUIDANCE,
    AudiogramParameters,
    AudiogramResult,
    AuditoryWeightingResult,
    ExposureCriteria,
    WeightedExposureResult,
    WeightingParameters,
    audiogram_parameters,
    auditory_weighting,
    exposure_criteria,
    group_audiogram,
    hearing_groups,
    orca_audiogram,
    weighted_exposure,
    weighting_parameters,
)
from .propagation import (
    WESTON_REGIMES,
    WESTON_SEABEDS,
    BottomLossResult,
    EigenrayResult,
    GaussianBeamResult,
    NormalModeResult,
    ParabolicEquationResult,
    PropagationLossResult,
    RayTraceResult,
    SeabedReflection,
    SoundSpeedProfile,
    WestonPropagationResult,
    WestonRegimeBoundaries,
    WestonSeabed,
    bottom_reflection_loss,
    critical_angle,
    critical_grazing_angle,
    depth_to_pressure,
    effective_depth,
    eigenrays,
    gaussian_beams,
    loss_parameter,
    normal_modes,
    parabolic_equation,
    propagation_loss,
    ray_trace,
    reflection_coefficient,
    reflection_loss_gradient,
    sea_water_sound_speed,
    seabed_reflection,
    seawater_absorption,
    sound_speed_profile,
    spreading_loss,
    waveguide_cutoff_frequency,
    weston_propagation_loss,
    weston_regime_boundaries,
)
from .sonar_equation import (
    DetectionRangeResult,
    SonarEquationResult,
    active_sonar_equation,
    detection_range,
    detection_range_from_curve,
    passive_sonar_equation,
)
from .sources import (
    VESSEL_CLASSES,
    AmbientNoiseResult,
    PileStrikeResult,
    ShipSourceLevelResult,
    ShipTrafficSpectrum,
    StrikeSelSpectrum,
    cumulative_sel,
    cumulative_sel_identical,
    hydrophone_depths,
    monopole_source_level,
    ocean_ambient_noise,
    pile_strike_metrics,
    radiated_noise_level,
    ship_source_spectrum,
    single_strike_sel,
    source_level_uncertainty,
    strike_sel_spectrum,
    thermal_noise_spectrum,
    wind_noise_spectrum,
)

__all__ = [
    "AUDIOGRAM_GROUPS",
    "BEST_HEARING_FREQUENCY_KHZ",
    "ORCA_AUDIOGRAM_RANGE_KHZ",
    "UNDERWATER_REFERENCE_EXPOSURE",
    "UNDERWATER_REFERENCE_PRESSURE",
    "VESSEL_CLASSES",
    "WEIGHTING_GUIDANCE",
    "WESTON_REGIMES",
    "WESTON_SEABEDS",
    "AmbientNoiseResult",
    "AudiogramParameters",
    "AudiogramResult",
    "AuditoryWeightingResult",
    "BottomLossResult",
    "DetectionRangeResult",
    "EigenrayResult",
    "ExposureCriteria",
    "GaussianBeamResult",
    "NormalModeResult",
    "ParabolicEquationResult",
    "PileStrikeResult",
    "PropagationLossResult",
    "RayTraceResult",
    "SeabedReflection",
    "ShipSourceLevelResult",
    "ShipTrafficSpectrum",
    "SonarEquationResult",
    "SoundSpeedProfile",
    "StrikeSelSpectrum",
    "WeightedExposureResult",
    "WeightingParameters",
    "WestonPropagationResult",
    "WestonRegimeBoundaries",
    "WestonSeabed",
    "active_sonar_equation",
    "audiogram_parameters",
    "auditory_weighting",
    "bottom_reflection_loss",
    "critical_angle",
    "critical_grazing_angle",
    "cumulative_sel",
    "cumulative_sel_identical",
    "depth_to_pressure",
    "detection_range",
    "detection_range_from_curve",
    "effective_depth",
    "eigenrays",
    "exposure_criteria",
    "gaussian_beams",
    "group_audiogram",
    "hearing_groups",
    "hydrophone_depths",
    "in_air_to_underwater_spl",
    "loss_parameter",
    "monopole_source_level",
    "normal_modes",
    "ocean_ambient_noise",
    "orca_audiogram",
    "parabolic_equation",
    "passive_sonar_equation",
    "peak_sound_pressure_level",
    "pile_strike_metrics",
    "propagation_loss",
    "radiated_noise_level",
    "ray_trace",
    "reflection_coefficient",
    "reflection_loss_gradient",
    "sea_water_sound_speed",
    "seabed_reflection",
    "seawater_absorption",
    "ship_source_spectrum",
    "single_strike_sel",
    "sound_exposure_level",
    "sound_pressure_level",
    "sound_speed_profile",
    "source_level_uncertainty",
    "spreading_loss",
    "strike_sel_spectrum",
    "thermal_noise_spectrum",
    "underwater_to_in_air_spl",
    "waveguide_cutoff_frequency",
    "weighted_exposure",
    "weighting_parameters",
    "weston_propagation_loss",
    "weston_regime_boundaries",
    "wind_noise_spectrum",
]

#: No public name left this namespace in 4.0, but the modules did, so
#: ``underwater.seabed_reflection`` has to keep resolving to its alias module
#: until 5.0: the import registers it, the attribute read needs this.
__getattr__ = _namespace_shim(__name__)
__dir__ = _namespace_dir(__name__, __all__)
