#  Copyright (c) 2026. Jose Manuel Requena Plens
"""noise_control domain of phonometry (see module docstrings)."""

from __future__ import annotations

from .._plot.geometry import (
    plot_plenum_geometry,
    plot_silencer_geometry,
)
from .duct_modes import (
    DuctModeResult,
    PlaneWaveWarning,
    circular_duct_cut_on,
    plane_wave_limit,
    rectangular_duct_cut_on,
)
from .duct_path import (
    DuctElement,
    DuctPathResult,
    DuctPathStage,
    combine_duct_paths,
    duct_path,
)
from .enclosures import (
    ENCLOSURE_MODELS,
    EnclosureResult,
    enclosure_insertion_loss,
    enclosure_required_transmission_loss,
)
from .hvac import (
    VDI2081_SPECTRAL_CORRECTION,
    HvacSpectrumResult,
    HvacWarning,
    air_terminal_damper_correction,
    air_terminal_velocity_limit,
    blade_passing_frequency,
    diffuser_sound_power,
    elbow_insertion_loss,
    end_reflection_loss,
    end_reflection_loss_closed_form,
    equivalent_diameter,
    fan_casing_attenuation,
    fan_efficiency_correction,
    fan_sound_power,
    flexible_duct_insertion_loss,
    flow_noise_bend,
    flow_noise_straight_duct,
    flow_noise_straight_duct_overall,
    lined_circular_duct_attenuation,
    lined_rectangular_duct_attenuation,
    octave_band_limits,
    plenum_attenuation,
    room_effect,
    section_change_loss,
    silencer_self_noise,
    split_loss,
    splitter_silencer_insertion_loss,
    unlined_circular_duct_attenuation,
    unlined_rectangular_duct_attenuation,
)
from .room_to_room import (
    DesignCriterion,
    RoomToRoomResult,
    SourceRoom,
    room_to_room_transmission,
)
from .silencers import (
    ReactiveSilencerResult,
    SilencerChain,
    SilencerChainElement,
    cascade,
    duct_matrix,
    expansion_chamber,
    extended_tube_chamber,
    helmholtz_impedance,
    helmholtz_resonator,
    insertion_loss,
    quarter_wave_impedance,
    quarter_wave_resonator,
    shunt_matrix,
    transmission_loss,
)

__all__ = [
    "DesignCriterion",
    "DuctElement",
    "DuctModeResult",
    "DuctPathResult",
    "DuctPathStage",
    "ENCLOSURE_MODELS",
    "EnclosureResult",
    "HvacSpectrumResult",
    "HvacWarning",
    "PlaneWaveWarning",
    "ReactiveSilencerResult",
    "RoomToRoomResult",
    "SilencerChain",
    "SilencerChainElement",
    "SourceRoom",
    "VDI2081_SPECTRAL_CORRECTION",
    "air_terminal_damper_correction",
    "air_terminal_velocity_limit",
    "blade_passing_frequency",
    "cascade",
    "circular_duct_cut_on",
    "combine_duct_paths",
    "diffuser_sound_power",
    "duct_matrix",
    "duct_path",
    "elbow_insertion_loss",
    "enclosure_insertion_loss",
    "enclosure_required_transmission_loss",
    "end_reflection_loss",
    "end_reflection_loss_closed_form",
    "equivalent_diameter",
    "expansion_chamber",
    "extended_tube_chamber",
    "fan_casing_attenuation",
    "fan_efficiency_correction",
    "fan_sound_power",
    "flexible_duct_insertion_loss",
    "flow_noise_bend",
    "flow_noise_straight_duct",
    "flow_noise_straight_duct_overall",
    "helmholtz_impedance",
    "helmholtz_resonator",
    "insertion_loss",
    "lined_circular_duct_attenuation",
    "lined_rectangular_duct_attenuation",
    "octave_band_limits",
    "plane_wave_limit",
    "plenum_attenuation",
    "plot_plenum_geometry",
    "plot_silencer_geometry",
    "quarter_wave_impedance",
    "quarter_wave_resonator",
    "rectangular_duct_cut_on",
    "room_effect",
    "room_to_room_transmission",
    "section_change_loss",
    "shunt_matrix",
    "silencer_self_noise",
    "split_loss",
    "splitter_silencer_insertion_loss",
    "transmission_loss",
    "unlined_circular_duct_attenuation",
    "unlined_rectangular_duct_attenuation",
]
